#!/usr/bin/env bash
# Generates briefs/proof/2.1/README.md: the vendor evaluation fixture walked through the
# engine (the route file built into a graph, each step applied with the state it changed and
# the events it emitted, a patch rejected with every violation by path, replay rebuilding the
# same records), the scenario matrix, and the planted bug (no tombstone on removal, caught by
# the B4 scenario's expected state, then passing again once restored). Exits non-zero if any
# outcome differs from the one expected.
#
# usage: briefs/proof/2.1/prove.sh WORK_DIR
#
# WORK_DIR holds a copy of the tree for the planted bug; the repository itself is never
# modified, apart from the README this writes.
# shellcheck disable=SC2016 # backticks in single quotes are Markdown code spans
set -euo pipefail
repo=$(cd "$(dirname "$0")/../../.." && pwd)
work=${1:?usage: prove.sh WORK_DIR}
mkdir -p "$work"
work=$(cd "$work" && pwd)
readme=$repo/briefs/proof/2.1/README.md
export CARGO_TERM_COLOR=never MISE_TRUSTED_CONFIG_PATHS=$work/tree
mismatches=0
out=$readme.tmp

cd "$repo"
cat >"$out" <<'EOF'
# Proof for brief 2.1: engine core

Generated by `briefs/proof/2.1/prove.sh WORK_DIR`; do not edit by hand. The script fails if
any outcome below differs from the one expected.

What this shows: the engine builds a graph from a route file, applies patches through its one
write path, and answers each with either a change set (one event per mutation, the next
revision) or a rejection listing every violation; the per-kind state machines allow exactly
their tables; and replay rebuilds the state from the events alone. The walkthrough below is
printed by `cargo run -p cairn-engine --example walkthrough -- fixtures`.

EOF

status=0
walkthrough=$(mise exec -- cargo run --quiet --locked -p cairn-engine --example walkthrough -- fixtures 2>&1) || status=$?
[ "$status" -eq 0 ] || { mismatches=$((mismatches + 1)); echo "prove.sh: the walkthrough failed: $walkthrough" >&2; }
grep -q 'rebuilds records equal to what apply produced: \*\*equal\*\*' <<<"$walkthrough" \
  || { mismatches=$((mismatches + 1)); echo "prove.sh: replay did not reproduce the state" >&2; }
printf '%s\n' "$walkthrough" >>"$out"

printf '\n## The scenario matrix and the state machines\n\n' >>"$out"
status=0
matrix=$(mise exec -- cargo test --quiet --locked -p cairn-engine --test matrix --test state_machines --test domains 2>&1) || status=$?
[ "$status" -eq 0 ] || { mismatches=$((mismatches + 1)); echo "prove.sh: the matrix failed" >&2; }
{
  printf 'Every J3 matrix entry this brief owns leaves its expected state and replays field by field after every step (`crates/engine/tests/matrix.rs`); apply allows every row of every D1 table and nothing else (`state_machines.rs`); every mutation type the patch format declares applies and emits its event (`domains.rs`, J2):\n\n```\n'
  grep -E '^test result' <<<"$matrix" | sed -E 's/; finished in .*//'
  printf '```\n'
} >>"$out"

printf '\n## Planted bug: no tombstone on removal\n\n' >>"$out"
tree=$work/tree
rsync -a --delete --exclude target --exclude node_modules --exclude .jj --exclude .git "$repo/" "$tree/"
removal=$tree/crates/engine/src/mutate/removal.rs
perl -0pi -e 's/if from_route\(session, key\) \{/if false && from_route(session, key) {/' "$removal"
if cmp -s "$removal" "$repo/crates/engine/src/mutate/removal.rs"; then
  mismatches=$((mismatches + 1))
  echo "prove.sh: the tombstone write was not found" >&2
fi
status=0
planted_output=$(cd "$tree" && mise exec -- cargo test --quiet -p cairn-engine --test matrix 2>&1) || status=$?
[ "$status" -ne 0 ] || { mismatches=$((mismatches + 1)); echo "prove.sh: the planted bug went unnoticed" >&2; }
# cp, not rsync -a: a fresh mtime makes cargo rebuild the restored file.
cp "$repo/crates/engine/src/mutate/removal.rs" "$removal"
status_after=0
after_output=$(cd "$tree" && mise exec -- cargo test --quiet -p cairn-engine --test matrix 2>&1) || status_after=$?
[ "$status_after" -eq 0 ] || { mismatches=$((mismatches + 1)); echo "prove.sh: the restored write fails" >&2; }
{
  printf 'In `crates/engine/src/mutate/removal.rs` the tombstone write is skipped (`if false && from_route(session, key)`), so removing a route-copied node records no tombstone in state or in its event. `cargo test -p cairn-engine --test matrix` exit status %s:\n\n```\n' "$status"
  grep -E 'panicked|route-copied nodes only|left:|right:|^test result' <<<"$planted_output" | sed -E 's/ \([0-9]+\)//; s/; finished in .*//' | head -6
  printf '```\n\nRestored, exit status %s:\n\n```\n' "$status_after"
  grep -E '^test result' <<<"$after_output" | sed -E 's/; finished in .*//'
  printf '```\n'
} >>"$out"

mv "$out" "$readme"
if [ "$mismatches" -gt 0 ]; then
  echo "prove.sh: $mismatches outcome(s) differed from the expected" >&2
  exit 1
fi
echo "prove.sh: every outcome was the expected one; wrote $readme"
