#!/usr/bin/env bash
# Generates briefs/proof/2.2/README.md: the fixtures walked through derive's passes 1 to 3
# (the vendor evaluation's relevance and participations at each decision point, checked
# against the tables fixtures/README.md states; the effective dependencies of nested nodes
# with each implicit edge's source; an effective skip with kept work; a role change
# re-deriving participations), the brief's test suites, and the planted bug (the child's
# wait on its parent's requirement entry dropped, caught by the scenario asserting the test
# plan's child actions wait for environment access, then passing again once restored).
# Exits non-zero if any outcome differs from the one expected.
#
# usage: briefs/proof/2.2/prove.sh WORK_DIR
#
# WORK_DIR holds a copy of the tree for the planted bug; the repository itself is never
# modified, apart from the README this writes.
# shellcheck disable=SC2016 # backticks in single quotes are Markdown code spans
set -euo pipefail
repo=$(cd "$(dirname "$0")/../../.." && pwd)
work=${1:?usage: prove.sh WORK_DIR}
mkdir -p "$work"
work=$(cd "$work" && pwd)
readme=$repo/briefs/proof/2.2/README.md
export CARGO_TERM_COLOR=never MISE_TRUSTED_CONFIG_PATHS=$work/tree
mismatches=0
out=$readme.tmp
miss() {
  mismatches=$((mismatches + 1))
  echo "prove.sh: $1" >&2
}

cd "$repo"
cat >"$out" <<'EOF'
# Proof for brief 2.2: relevance, effective dependencies, effective skip, participation

Generated by `briefs/proof/2.2/prove.sh WORK_DIR`; do not edit by hand. The script fails if
any outcome below differs from the one expected.

What this shows: `derive` now answers, for any journey, which nodes are in scope and why
(three-valued relevance naming the condition or force include that produced it), what each
node waits on and why (the effective dependency graph, every implicit edge tagged with its
source and typed gate or date-only, with ancestors' requirements reaching descendants through
the entry chain), which work an ancestor's skip covers and which kept work it still waits
on, and who is involved (participations resolved in E2's order, `unassigned`, and the
membership-loss flag). The tables below are printed by
`cargo run -p cairn-engine --example derive_walkthrough -- fixtures`.

EOF

status=0
walkthrough=$(mise exec -- cargo run --quiet --locked -p cairn-engine --example derive_walkthrough -- fixtures 2>&1) || status=$?
[ "$status" -eq 0 ] || miss "the walkthrough failed: $walkthrough"
printf '%s\n' "$walkthrough" >>"$out"

# The decision-point tables are what fixtures/README.md states, row for row.
stated=0
while IFS= read -r line; do
  grep -qxF -- "$line" fixtures/README.md || miss "fixtures/README.md does not state: $line"
  stated=$((stated + 1))
done < <(awk '/^## Relevance at each/ { p = 1 } /^## Effective dependencies/ { p = 0 } p && /^\|/' <<<"$walkthrough")
[ "$stated" -gt 0 ] || miss "no decision-point table rows were printed"
printf '\nThe %s rows of the two decision-point tables above are the ones `fixtures/README.md` states for the vendor evaluation; the J3 matrix entry "vendor evaluation: relevance and owners at each decision point" checks the same values.\n' "$stated" >>"$out"

printf '\n## The suites\n\n' >>"$out"
status=0
suites=$(mise exec -- cargo test --quiet --locked -p cairn-engine --all-features \
  --test relevance --test dependencies --test skip --test participation --test matrix \
  --test property_derive --test property_dependencies 2>&1) || status=$?
[ "$status" -eq 0 ] || miss "the suites failed"
{
  printf 'Relevance, the effective dependency graph, effective skip, and participation by example, the J3 matrix with this brief'"'"'s entries, and the property tests over generated deep trees, among them the reference test of the entry chain against the plain expansion. In cargo'"'"'s order: `dependencies.rs`, `matrix.rs`, `participation.rs`, `property_dependencies.rs`, `property_derive.rs`, `relevance.rs`, `skip.rs`:\n\n```\n'
  grep -E '^test result' <<<"$suites" | sed -E 's/; finished in .*//'
  printf '```\n'
} >>"$out"

printf '\n## Planted bug: a child no longer waits on its parent'"'"'s entry\n\n' >>"$out"
tree=$work/tree
rsync -a --delete --exclude target --exclude node_modules --exclude .jj --exclude .git "$repo/" "$tree/"
graph=$tree/crates/engine/src/derive/dependencies.rs
perl -0pi -e 's/\(\s*self\.anchor\(at\),\s*instant\(parent, Point::Entry\),\s*EdgeSource::Chain,\s*\),//' "$graph"
cmp -s "$graph" "$repo/crates/engine/src/derive/dependencies.rs" && miss "the chain link was not found"
status=0
planted_output=$(cd "$tree" && mise exec -- cargo test --quiet --all-features -p cairn-engine --test dependencies 2>&1) || status=$?
[ "$status" -ne 0 ] || miss "the planted bug went unnoticed"
grep -q 'a_childs_actions_wait_for_their_parents_requirement' <<<"$planted_output" \
  || miss "the scenario asserting the plan's actions wait for access did not fail"
# cp, not rsync -a: a fresh mtime makes cargo rebuild the restored file.
cp "$repo/crates/engine/src/derive/dependencies.rs" "$graph"
status_after=0
after_output=$(cd "$tree" && mise exec -- cargo test --quiet --all-features -p cairn-engine --test dependencies 2>&1) || status_after=$?
[ "$status_after" -eq 0 ] || miss "the restored link fails"
{
  printf 'In `crates/engine/src/derive/dependencies.rs` the link from a child'"'"'s requirement anchor to its parent'"'"'s requirement entry is removed, so an ancestor'"'"'s requirement no longer reaches its descendants. `cargo test -p cairn-engine --test dependencies` exit status %s:\n\n```\n' "$status"
  grep -E "^thread 'a_childs_actions|^test result|^    a_childs" <<<"$planted_output" | sed -E "s/ \\([0-9]+\\)//; s/; finished in .*//" | head -6
  printf '```\n\nRestored, exit status %s:\n\n```\n' "$status_after"
  grep -E '^test result' <<<"$after_output" | sed -E 's/; finished in .*//'
  printf '```\n'
} >>"$out"

mv "$out" "$readme"
if [ "$mismatches" -gt 0 ]; then
  echo "prove.sh: $mismatches outcome(s) differed from the expected" >&2
  exit 1
fi
echo "prove.sh: every outcome was the expected one; wrote $readme"
