#!/usr/bin/env bash
# Generates briefs/proof/4.1/README.md: the vendor evaluation's route published and its
# journey created, patched, conflicted, retried, resubmitted after a lost response, given a
# patch with consequences, and read back, through the service over the memory store and a
# Turso file (`cargo run -p cairn-service --example service_proof`), with the ticks a
# subscriber heard; the service's test suites with their counts; and the planted bug (the
# receipt never looked up, caught by the H5 resubmission test, then passing again once
# restored). Exits non-zero if any outcome differs from the one expected.
#
# usage: briefs/proof/4.1/prove.sh WORK_DIR
#
# WORK_DIR holds the proof's Turso file and a copy of the tree for the planted bug; the
# repository itself is never modified, apart from the README this writes.
# shellcheck disable=SC2016 # backticks in single quotes are Markdown code spans
set -euo pipefail
repo=$(cd "$(dirname "$0")/../../.." && pwd)
work=${1:?usage: prove.sh WORK_DIR}
mkdir -p "$work"
work=$(cd "$work" && pwd)
tree=$work/tree
readme=$repo/briefs/proof/4.1/README.md
export CARGO_TERM_COLOR=never MISE_TRUSTED_CONFIG_PATHS=$tree
mismatches=0
out=$readme.tmp
miss() {
  mismatches=$((mismatches + 1))
  echo "prove.sh: $1" >&2
}

cd "$repo"
cat >"$out" <<'HEADER'
# Proof for brief 4.1: the service layer

Generated by `briefs/proof/4.1/prove.sh WORK_DIR`; do not edit by hand. The script fails if
any outcome below differs from the one expected.

What this shows: a host can now hand a patch to one service and get back what the PRD
promises, over either store. The service answers a resubmitted patch id from its receipt
before loading anything, loads exactly what the patch reads, applies it through the engine,
works out what it newly caused (D7), commits it with every revision it read rechecked, and
announces each revision the commit moved to its subscribers. Below, the vendor evaluation
fixture runs through `Service::patch` (`cargo run -p cairn-service --example
service_proof`): its route published as version 1, its journey created and its up-front
decisions answered by the scenario's first two steps, then a second person's note drafted
before those answers (stale, and safe to retry on its own), the retry, the retry resubmitted
after a lost response, progress on the setup stage, and an agent inserting a dependency
under finished work. A subscriber watching every journey, route, and the deployment takes
its ticks after each write.

HEADER

db=$work/proof.db
rm -f "$db" "$db"-*
status=0
mise exec -- cargo run --quiet --locked -p cairn-service --example service_proof -- "$db" >"$work/walk.md" 2>"$work/walk.err" || status=$?
[ "$status" -eq 0 ] || { cat "$work/walk.err" >&2; miss "the walkthrough failed"; }
cat "$work/walk.md" >>"$out"
grep -q 'the same way: \*\*yes\*\*' "$work/walk.md" || miss "the two stores answered differently"
grep -q 'engine.s own run of the same patches: \*\*true\*\*' "$work/walk.md" || miss "the journey read back differs from the engine's"

printf '## The suites\n\n' >>"$out"
status=0
tests=$(mise exec -- cargo test --locked -p cairn-service --all-features 2>&1) || status=$?
[ "$status" -eq 0 ] || miss "the service's tests failed"
{
  printf 'The service'"'"'s tests (`cargo test -p cairn-service`; the write cases run once over each store), exit status %s:\n\n```\n' "$status"
  grep -E '^ *Running |^test result' <<<"$tests" | sed -E 's/ \(target[^)]*\)//; s/; finished in [0-9.]+s//'
  printf '```\n\n'
} >>"$out"

printf '## The planted bug\n\n' >>"$out"
rsync -a --delete --exclude target --exclude node_modules --exclude .jj --exclude .git "$repo/" "$tree/"
write=$tree/crates/service/src/write.rs
perl -0pi -e 's/let Some\(receipt\) = self\.store\.receipt\(&patch\.id\)\.await\? else/let Some(receipt) = None::<PatchReceipt> else/' "$write"
cmp -s "$write" "$repo/crates/service/src/write.rs" && miss "the planted bug was not planted"
case_name=memory::a_resubmission_after_another_patch_is_answered_from_its_receipt
status=0
planted=$(cd "$tree" && mise exec -- cargo test --quiet --locked -p cairn-service --test writes -- "$case_name" 2>&1) || status=$?
[ "$status" -ne 0 ] || miss "the planted bug went unnoticed"
# cp, not rsync -a: a fresh mtime makes cargo rebuild the restored file.
cp "$repo/crates/service/src/write.rs" "$write"
status_after=0
after=$(cd "$tree" && mise exec -- cargo test --quiet --locked -p cairn-service --test writes -- "$case_name" 2>&1) || status_after=$?
[ "$status_after" -eq 0 ] || miss "the restored service fails"
{
  printf 'In `crates/service/src/write.rs`, the patch receipt is never looked up, so a lost-response resubmission whose journey moved on meanwhile reaches `apply` and is answered stale instead of from its receipt (H5). `%s` exit status %s:\n\n```\n' "$case_name" "$status"
  grep -E 'panicked|^ *left|^test result' <<<"$planted" | sed -E 's/ \([0-9]+\)//; s/intervening: TouchedSet\(.*\) \}/intervening: ... }/; s/; finished in [0-9.]+s//' | head -4
  printf '```\n\nRestored, exit status %s:\n\n```\n' "$status_after"
  grep -E '^test result' <<<"$after" | sed -E 's/; finished in [0-9.]+s//'
  printf '```\n'
} >>"$out"

mv "$out" "$readme"
if [ "$mismatches" -gt 0 ]; then
  echo "prove.sh: $mismatches outcome(s) differed from the expected" >&2
  exit 1
fi
echo "prove.sh: every outcome was the expected one; wrote $readme"
