//! Proposals' request and response bodies (I6, C14; ARCHITECTURE, HTTP API: Resources):
//! created against a domain with a client-generated id, edited and discarded against their
//! own editing revision, previewed, applied, and refreshed; upgrades, saves as route, and
//! re-links drafted by the engine as proposals (B7, B8, B9); and route files imported (A13).
//! Every write names a client patch id, so a lost response is resubmitted rather than guessed
//! at (H5).

use std::collections::BTreeMap;

use cairn_schema::{
    Consequences, JourneyId, Lineage, Markdown, PatchId, PatchReceipt, Proposal, ProposalDraft,
    ProposalId, ProposalPreview, Revision, RevisionConflict, RouteFile, RouteId, Title, TouchedSet,
    VersionNumber,
};
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

/// `POST /api/{domain}/proposals`: a new proposal for the path's domain (which may not exist yet:
/// a proposal can create a journey or route at revision 0).
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ProposalCreate {
    /// The write's patch id (H5).
    pub patch_id: PatchId,
    /// The proposal's id, generated by the client (I6): a create resubmitted under it answers
    /// the proposal its caller already holds rather than a second one.
    pub id: ProposalId,
    /// Its content.
    pub draft: ProposalDraft,
}

/// `PATCH /api/proposals/{id}`: the proposal's new content, against the editing revision the
/// editor saw (H5). Its destination's revision does not move.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ProposalEdit {
    /// The write's patch id (H5).
    pub patch_id: PatchId,
    /// The proposal's editing revision the editor saw.
    pub base_revision: Revision,
    /// Its content.
    pub draft: ProposalDraft,
}

/// `POST /api/proposals/{id}/discard` and `POST /api/proposals/{id}/refresh`: against the editing
/// revision the caller saw.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ProposalStep {
    /// The write's patch id (H5).
    pub patch_id: PatchId,
    /// The proposal's editing revision the caller saw.
    pub base_revision: Revision,
}

/// `POST /api/proposals/{id}/apply`: applies the proposal as the caller, its confirming user
/// (H2), at the editing revision they reviewed.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ProposalApply {
    /// The apply's patch id (H5).
    pub patch_id: PatchId,
    /// The proposal's editing revision the reviewer previewed.
    pub reviewed_revision: Revision,
    /// A note for each of the apply's events (J1).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub note: Option<Markdown>,
}

/// What a write to a proposal answers (I6).
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(tag = "outcome", rename_all = "snake_case", deny_unknown_fields)]
pub enum ProposalAnswer {
    /// Committed now: the receipt (its revision is the proposal's editing revision) and the
    /// proposal as it now stands.
    Saved {
        /// The receipt.
        receipt: PatchReceipt,
        /// The proposal.
        proposal: Proposal,
    },
    /// The patch id was committed before with the same content (H5): its receipt; fetch the
    /// proposal by id for where it stands now.
    AlreadySaved {
        /// The original receipt.
        receipt: PatchReceipt,
    },
    /// I6: a create naming a proposal id its caller already holds for this destination: that
    /// proposal as it stands, not a second one.
    Existing {
        /// The proposal.
        proposal: Proposal,
    },
}

impl From<cairn_service::ProposalWritten> for ProposalAnswer {
    fn from(written: cairn_service::ProposalWritten) -> Self {
        match written {
            cairn_service::ProposalWritten::Saved { receipt, proposal } => {
                ProposalAnswer::Saved { receipt, proposal }
            }
            cairn_service::ProposalWritten::AlreadySaved { receipt } => {
                ProposalAnswer::AlreadySaved { receipt }
            }
            cairn_service::ProposalWritten::Existing { proposal } => {
                ProposalAnswer::Existing { proposal }
            }
        }
    }
}

impl ProposalAnswer {
    /// The outcome, as the patch count and logs name it.
    #[must_use]
    pub fn outcome(&self) -> &'static str {
        match self {
            ProposalAnswer::Saved { .. } => "saved",
            ProposalAnswer::AlreadySaved { .. } => "already_saved",
            ProposalAnswer::Existing { .. } => "existing",
        }
    }
}

/// `POST /api/proposals/{id}/preview` (C14, D7, I6): what applying the proposal now would do, and,
/// when its destination moved since it was drafted, what moved.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ProposalReview {
    /// The proposal, at the editing revision a reviewer applies.
    pub proposal: Proposal,
    /// Its items still unresolved, the violations of its candidate, and for a journey the
    /// graph and frontier after.
    pub preview: ProposalPreview,
    /// D7, by journey: what applying it would newly cause; a journey with nothing new is left
    /// out.
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub consequences: BTreeMap<JourneyId, Consequences>,
    /// I6: present when the destination moved since drafting: applying it is stale until it
    /// is refreshed and reviewed again.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub stale: Option<StaleBase>,
}

/// I6: a proposal's destination moved past the revision it was drafted against.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct StaleBase {
    /// The destination's revision the proposal names, and its current one.
    pub conflict: RevisionConflict,
    /// What the intervening events touched (H5).
    pub intervening: TouchedSet,
}

impl From<cairn_service::ProposalReview> for ProposalReview {
    fn from(review: cairn_service::ProposalReview) -> Self {
        let cairn_service::ProposalReview {
            proposal,
            preview,
            consequences,
            stale,
        } = review;
        Self {
            proposal,
            preview,
            consequences,
            stale: stale.map(|stale| StaleBase {
                conflict: stale.conflict,
                intervening: stale.intervening,
            }),
        }
    }
}

/// `POST /api/journeys/{id}/upgrade` (B7): proposes upgrading the journey to a newer version of
/// the route it follows.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct UpgradeRequest {
    /// The proposal write's patch id (H5).
    pub patch_id: PatchId,
    /// The proposal's id, generated by the client (I6).
    pub proposal: ProposalId,
    /// The version to upgrade to.
    pub to: VersionNumber,
}

/// `POST /api/journeys/{id}/save-as-route` (B8): proposes saving the journey's structure as a
/// draft of a route, created when it does not exist.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct SaveAsRouteRequest {
    /// The proposal write's patch id (H5).
    pub patch_id: PatchId,
    /// The proposal's id, generated by the client (I6).
    pub proposal: ProposalId,
    /// The route the draft is of.
    pub route: RouteId,
    /// The route's name, when it is created.
    pub name: Title,
}

/// `POST /api/journeys/{id}/relink` (B9): proposes re-linking the journey to a published version.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct RelinkRequest {
    /// The proposal write's patch id (H5).
    pub patch_id: PatchId,
    /// The proposal's id, generated by the client (I6).
    pub proposal: ProposalId,
    /// The route version to follow once it is applied.
    pub lineage: Lineage,
}

/// `POST /api/routes/{id}/import` (A13): a route file, imported as a new route or a new draft of
/// the path's route, matched against the version it extends.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct RouteImport {
    /// The import's patch id (H5): the same file under the same id is the same patch.
    pub patch_id: PatchId,
    /// The file, as JSON (ARCHITECTURE, File format); its route must be the path's.
    pub file: RouteFile,
    /// A note for each of its events (J1).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub note: Option<Markdown>,
}
