#!/usr/bin/env bash
# Generates briefs/proof/4.6/: the README, a screenshot of each acceptance state of the app
# shell, and a short video of its main flow. Builds the module (mise run build:wasm) and the
# fixture server, runs the web unit tests (Vitest) and the app's browser tests (Playwright,
# rung 6's web/app suite) keeping their counts, runs the proof's pictures
# (web/app/proof/shell.proof.ts), then the planted bug: the tracker comparing ticks with the
# revision fetched first instead of the one held now, caught by "a later page shows the edit".
# The plant is made in place and always restored (checked byte for byte). Exits non-zero if
# any outcome differs from the one expected.
#
# usage: briefs/proof/4.6/prove.sh
# shellcheck disable=SC2016 # backticks in single quotes are Markdown code spans
set -euo pipefail
repo=$(cd "$(dirname "$0")/../../.." && pwd)
proof=$repo/briefs/proof/4.6
work=$repo/web/app/dist/prove
readme=$proof/README.md
export CARGO_TERM_COLOR=never
mismatches=0
miss() {
  mismatches=$((mismatches + 1))
  echo "prove.sh: $1" >&2
}
cd "$repo"
rm -rf "$work"
mkdir -p "$work"

mise run build:wasm
mise exec -- cargo build --quiet --locked -p cairn-wasm --example fixture_server

# The web unit tests, per package: passed, failed.
unit_rows=""
for package in web/client web/app; do
  report=$work/vitest-$(basename "$package").json
  (cd "$package" && "$repo/node_modules/.bin/vitest" run --reporter=json --outputFile.json="$report" >/dev/null) \
    || miss "the web unit tests of $package failed"
  unit_rows+=$(node -e '
    const r = JSON.parse(require("fs").readFileSync(process.argv[1], "utf8"));
    console.log(`| \`${process.argv[2]}\` | ${r.numPassedTests} passed, ${r.numFailedTests} failed |`);' "$report" "$package")$'\n'
done

# The app's browser tests: each test and its outcome.
e2e=$work/playwright.json
(cd web/app && PLAYWRIGHT_JSON_OUTPUT_NAME=$e2e "$repo/node_modules/.bin/playwright" test --reporter=json >/dev/null) \
  || miss "the app's browser tests failed"
e2e_rows=$(node -e '
  const report = JSON.parse(require("fs").readFileSync(process.argv[1], "utf8"));
  const walk = (suite, file) => [
    ...(suite.specs ?? []).map((spec) => `| ${file} | ${spec.title} | ${spec.ok ? "passed" : "failed"} |`),
    ...(suite.suites ?? []).flatMap((inner) => walk(inner, file)),
  ];
  for (const suite of report.suites) for (const row of walk(suite, suite.title.replace(/\.spec\.ts$/, ""))) console.log(row);
' "$e2e")

# The pictures.
rm -f "$proof"/*.png "$proof"/*.webm
(cd web/app && CAIRN_PROOF_OUT=$proof "$repo/node_modules/.bin/playwright" test -c playwright.proof.config.ts proof/shell.proof.ts --reporter=line) \
  || miss "the proof run failed"
rm -rf "$proof/video"
for picture in 1-index-in-browser 2-journey-derived-in-worker 3a-patch-saved-with-consequences \
  3b-other-tab-updated-live 4-conflict-surfaced 5-version-skew-banner 6-draft-survives-reload; do
  [ -s "$proof/$picture.png" ] || miss "the picture $picture is missing"
done
[ -s "$proof/main-flow.webm" ] || miss "the main flow's video is missing"

# The planted bug, in place, restored on any exit.
tracker=web/client/src/tracker.ts
cp "$tracker" "$work/tracker.ts"
restore() { cp "$work/tracker.ts" "$repo/$tracker"; }
trap restore EXIT
sed -i 's/const held = Math.max(this.#held.get(name) ?? revision, revision);/const held = this.#held.get(name) ?? revision;/' "$tracker"
cmp -s "$tracker" "$work/tracker.ts" && miss "the planted bug was not planted"
status=0
planted=$(cd web/app && "$repo/node_modules/.bin/playwright" test -g "a later page shows the edit" --reporter=line 2>&1) || status=$?
restore
trap - EXIT
cmp -s "$tracker" "$work/tracker.ts" || miss "the tracker was not restored"
[ "$status" -ne 0 ] || miss "the planted bug went unnoticed"
caught=$(grep -E '^\s+(Expected|Received):' <<<"$planted" | sed 's/^ *//' | paste -sd ' ' -)
[ -n "$caught" ] || miss "the planted bug's failure was not found"

out=$readme.tmp
{
  cat <<'EOF'
# Proof for brief 4.6: Web client and app shell

Generated by `briefs/proof/4.6/prove.sh`; do not edit by hand. The script fails if any
outcome below differs from the one expected.

Cairn now has a web app. It runs over the server (here the API over the fixtures,
`crates/wasm/examples/fixture_server.rs`, behind Vite's proxy) or over the in-browser host
with no server at all, and one data layer reads either: each journey's domain document is
fetched once per revision and derived in the derive worker, writes go through the client's
safe retry (H5) with their consequences shown (D7), and every open view follows the host's
revision ticks (H6), refetching only what moved. A tab whose engine is older than a document
it fetched stops deriving and writing and asks for a reload, and nothing typed is lost.

## The shell's states

The journey index, seeded from the fixtures, on the in-browser host:

![The journey index on the in-browser host](1-index-in-browser.png)

A journey's document derived in the derive worker (the derivation line names the revision,
deployment revision, and today it was derived for):

![A journey derived in the worker](2-journey-derived-in-worker.png)

A rename saved through the write path, with its consequences notice (D7), and the same
journey in another tab, updated with no reload (H6):

![The saved patch and its notice](3a-patch-saved-with-consequences.png)

![The other tab, updated live](3b-other-tab-updated-live.png)

Two tabs renaming the same node: the second save is not retried, since what intervened
touched what it touches (H5); the change is shown and the draft kept:

![A conflict surfaced](4-conflict-surfaced.png)

A document from a newer engine (`99.0.0`, as a server deployed meanwhile would send): the
tab stops deriving, saving, and retrying, and asks for a reload:

![The version-skew banner](5-version-skew-banner.png)

After the reload, the unsent rename is still there (drafts are kept per tab in session
storage):

![The draft after the reload](6-draft-survives-reload.png)

The main flow, on the server host: the index, a journey, a rename and its notice, and
another tab's rename arriving live: [main-flow.webm](main-flow.webm).

## The tests

Web unit tests (Vitest, rung 6): the safe retry and the tracker case for case with the Rust
client's, the tick stream's reopening, and the data layer over a fake host.

| Package | Result |
|---|---|
EOF
  printf '%s' "$unit_rows"
  cat <<'EOF'

The app's browser tests (Playwright in Chromium, rung 6), over both hosts:

| File | Test | Result |
|---|---|---|
EOF
  printf '%s\n' "$e2e_rows"
  cat <<'EOF'

## The planted bug

The tracker comparing each tick with the revision the view fetched first instead of the one
it holds now (`Tracker.fetched` never raising what it holds): the page that comes back to a
journey refetches revisions it already has, and "a later page shows the edit", which counts
the page's document fetches (H6: refetch only when the announced revision is newer), fails:

```text
EOF
  printf '%s\n' "$caught"
  echo '```'
} >"$out"
mv "$out" "$readme"
if [ "$mismatches" -ne 0 ]; then
  echo "prove.sh: $mismatches outcomes differ from those expected" >&2
  exit 1
fi
echo "prove.sh: wrote $readme"
