//! The JSON Schema for the file format (ARCHITECTURE, File format; Generated artifacts):
//! generated from [`RouteFile`], the type that parses route files, so the published schema
//! and the parser describe one format. `mise run gen` writes it to `schema/`.

use schemars::generate::SchemaSettings;
use serde_json::Value;

use crate::graph::RouteFile;

/// The generated files, as (file name, content).
#[must_use]
pub fn generated_files() -> Vec<(&'static str, String)> {
    vec![("route-file.schema.json", route_file())]
}

/// The route file's JSON Schema (draft 2020-12), pretty-printed with a trailing newline.
///
/// # Panics
///
/// Never: a schema always serializes.
#[must_use]
pub fn route_file() -> String {
    let generator = SchemaSettings::draft2020_12().into_generator();
    let schema = generator.into_root_schema_for::<RouteFile>();
    let mut value = schema.to_value();
    if let Value::Object(map) = &mut value {
        map.insert(
            "$comment".to_owned(),
            Value::String(
                "Generated by `mise run gen` from crates/schema (RouteFile); do not edit by hand."
                    .to_owned(),
            ),
        );
        map.insert(
            "$id".to_owned(),
            Value::String(
                "https://github.com/JacobHayes/cairn/schema/route-file.schema.json".to_owned(),
            ),
        );
    }
    match crate::document::to_json_pretty(&value) {
        Ok(text) => text,
        Err(error) => panic!("a schema always serializes: {error}"),
    }
}
