#!/usr/bin/env bash
# Generates briefs/proof/4.4/README.md: the assistant over HTTP, recorded as the API's own
# tests send their requests to a server on loopback (crates/api/tests/support/transcript.rs)
# with a scripted model provider: the capabilities document without and with the assistant;
# then one conversation that structures an ad-hoc journey through a proposal the user
# applies, makes a direct state change reported with its consequences, has a request
# touching more than ten nodes turned into one proposal, and reports a provider that stops
# answering. Then each wire protocol's round trip against its fixture, the test counts, and
# the planted bug (a structural write let through the wrapper on one tool, caught by the
# policy tests). Exits non-zero if any outcome differs from the one expected.
#
# usage: briefs/proof/4.4/prove.sh WORK_DIR
#
# WORK_DIR holds the transcripts and a copy of the tree for the planted bug; the repository
# itself is never modified, apart from the README this writes.
# shellcheck disable=SC2016 # backticks in single quotes are Markdown code spans
set -euo pipefail
repo=$(cd "$(dirname "$0")/../../.." && pwd)
work=${1:?usage: prove.sh WORK_DIR}
mkdir -p "$work"
work=$(cd "$work" && pwd)
readme=$repo/briefs/proof/4.4/README.md
export CARGO_TERM_COLOR=never MISE_TRUSTED_CONFIG_PATHS=$work/tree
mismatches=0
out=$readme.tmp
transcripts=$work/transcripts
rm -rf "$transcripts"
mkdir -p "$transcripts"
miss() {
  mismatches=$((mismatches + 1))
  echo "prove.sh: $1" >&2
}

cd "$repo"
cat >"$out" <<'EOF'
# Proof for brief 4.4: Assistant

Generated by `briefs/proof/4.4/prove.sh WORK_DIR`; do not edit by hand. The script fails if
any outcome below differs from the one expected.

What this shows: a deployment that configures a model provider now offers the in-app
assistant (I5) at `POST /journeys/{id}/assistant` and `POST /routes/{id}/draft/assistant`,
and says so in its capabilities document; one without a provider serves neither and says
so. A turn runs the MCP tool set in process as the assistant acting for the signed-in user
(I7, H2), and every tool call passes through one write wrapper: structural changes, and
state changes touching more than ten nodes, arrive as one proposal for the user to review
and apply; other state changes apply directly and come back with their consequences (D7).

Each section is the transcript of one of `crates/api/tests/assistant.rs`'s tests, recorded
as it ran against a server on loopback over the memory store: the request as the curl
command that would send it, and the response. The model is a scripted provider (no network,
no credential); a note before each turn says which tools it calls. Ann signs in with a test
provider that stands for any provider vouching for a verified email (`Bearer team-ann`).
User ids are minted at random, so they differ from run to run; request ids are masked
(`rq_…`) and long bodies cut.
EOF

# Runs one assistant API test with its transcript on; appends the transcript under a heading.
section() {
  local title=$1 test=$2 note=$3 status=0
  mise exec -- env CAIRN_API_TRANSCRIPT="$transcripts" \
    cargo test --quiet --locked -p cairn-api --test assistant -- --exact "in_process::$test" \
    >"$work/assistant-$test.log" 2>&1 || status=$?
  local transcript=$transcripts/in_process__$test.md
  [ "$status" -eq 0 ] && [ -s "$transcript" ] || miss "assistant::$test failed or recorded nothing"
  {
    printf '\n## %s\n\n%s (`crates/api/tests/assistant.rs`, `%s`, exit status %s.)\n\n' "$title" "$note" "$test" "$status"
    cat "$transcript" 2>/dev/null || true
  } >>"$out"
}

section 'The capabilities document, without and with the assistant' the_capabilities_say_whether_the_assistant_is_served \
  'I5 (fully usable without the assistant): first a root assembled with no provider, whose capabilities say `"assistant": false` and which answers 404 at both assistant endpoints; then a root with one, whose capabilities say `"assistant": true` and which answers a turn at each'

section 'A conversation' a_conversation_structures_reports_proposes_and_times_out \
  'I5, I7, H2, D7, and the PRD success criterion with no route: the bake-off fixture'"'"'s empty journey is structured by one proposal the user applies (the applied events name the assistant acting for the user, and the user confirming); the vendor evaluation'"'"'s up-front decisions are answered directly and the answer is reported with the shortfalls it caused; eleven weight overrides become one proposal and nothing lands; and a provider that stops answering ends the turn as timed out once the 120 s provider call limit passes (in the test'"'"'s paused clock), with the write made before it standing and reported'

printf '\n## The wire protocols\n\n' >>"$out"
status=0
protocols=$(mise exec -- cargo test --locked -p cairn-assistant --test protocols 2>&1) || status=$?
[ "$status" -eq 0 ] || miss "the protocol round trips failed"
{
  printf 'Each protocol sends a conversation and its tools to a loopback server standing in for the provider, which holds the request to the fixture'"'"'s body and headers and answers the fixture'"'"'s response: a tool call, then, once the tool'"'"'s result is sent back in the protocol'"'"'s own shape, the final text (`crates/assistant/tests/protocols.rs`, exit status %s). The fixtures were written from each provider'"'"'s public API reference, not captured live, since that needs a credential (DECISIONS.md, 4.4):\n\n| Protocol | Fixture | Source |\n|---|---|---|\n' "$status"
  for fixture in anthropic-messages openai-responses chat-completions; do
    file=crates/assistant/tests/fixtures/$fixture.json
    source=$(node -e 'console.log(JSON.parse(require("fs").readFileSync(process.argv[1], "utf8")).source)' "$file")
    printf '| `%s` | `%s` | %s |\n' "$fixture" "$file" "$source"
  done
  printf '\n```\n'
  grep -E '^test |^test result' <<<"$protocols" | sed -E 's/; finished in .*//'
  printf '```\n'
} >>"$out"

printf '\n## The tests\n\n' >>"$out"
status=0
tests=$(mise exec -- cargo test --locked -p cairn-assistant 2>&1) || status=$?
[ "$status" -eq 0 ] || miss "the assistant's tests failed"
status_api=0
endpoint=$(mise exec -- cargo test --locked -p cairn-api --test assistant 2>&1) || status_api=$?
[ "$status_api" -eq 0 ] || miss "the endpoints' tests failed"
{
  printf '`cargo test -p cairn-assistant` (rung 2), exit status %s, and `cargo test -p cairn-api --test assistant` (its `in_process` suite, rung 4), exit status %s:\n\n| Suite | Passed |\n|---|---|\n' "$status" "$status_api"
  awk '/^ *Running unittests/ { suite = $3 } /^ *Running tests\// { suite = $2 } /^ *Doc-tests/ { suite = "" }
       /^test result:/ && suite != "" { print "| `" suite "` | " $4 " |" }' <<<"$tests"$'\n'"$endpoint"
} >>"$out"
cat >>"$out" <<'EOF'

`tests/policy.rs` decides every write tool the tool set lists, a structural variant wherever
the tool can carry one, and checks the cases cover exactly the write tools, so a write tool
added later fails it until it is decided; it then runs every write that must become a
proposal and checks that neither the journey nor the route moved. `tests/turns.rs` drives
turns with the scripted model: the success criterion with no route, a direct write's
consequences and attribution, the bulk proposal, a route drafted in conversation as a
proposal on its draft (A12), the per-member breakdown's explicit participations (B10), the
provider timeout, the iteration, duration, and in-flight limits, an agent caller refused, and
conversations one per target per user.
EOF

printf '\n## Planted bug: a structural write let through on one tool\n\n' >>"$out"
tree=$work/tree
rsync -a --delete --exclude target --exclude node_modules --exclude .jj --exclude .git "$repo/" "$tree/"
wrapper=$tree/crates/assistant/src/wrapper.rs
perl -0pi -e 's/(    if drafted\.patch\(\)\.change_class\(\) == ChangeClass::Structural \{)/    if name == "resolve_date_conflict" {\n        let (nodes, current) = (BTreeSet::new(), None);\n        return Ok(Decision::Direct { drafted, nodes, current });\n    }\n$1/' "$wrapper"
cmp -s "$wrapper" "$repo/crates/assistant/src/wrapper.rs" && miss "the planted bug was not planted"
policy=(cargo test --locked -p cairn-assistant --test policy)
status=0
planted=$(cd "$tree" && mise exec -- "${policy[@]}" 2>&1) || status=$?
[ "$status" -ne 0 ] || miss "the planted bug went unnoticed"
cp "$repo/crates/assistant/src/wrapper.rs" "$wrapper"
status_after=0
after=$(cd "$tree" && mise exec -- "${policy[@]}" 2>&1) || status_after=$?
[ "$status_after" -eq 0 ] || miss "the restored tree fails the policy tests"
{
  printf 'In `crates/assistant/src/wrapper.rs`, `decide` lets `resolve_date_conflict` apply directly whatever its resolution (`if name == "resolve_date_conflict" { return Ok(Decision::Direct { .. }); }` before the structural check). The policy tests, exit status %s:\n\n```\n' "$status"
  grep -E '^resolve_date_conflict|^test .*FAILED|^test result' <<<"$planted" | sed -E 's/; finished in .*//; s/Outcome \{ answer: Err\(Rejected.*/Outcome { answer: Err(Rejected { .. }), action: None }/'
  printf '```\n\nRestored, exit status %s:\n\n```\n' "$status_after"
  grep -E '^test result' <<<"$after" | sed -E 's/; finished in .*//'
  printf '```\n'
} >>"$out"

mv "$out" "$readme"
if [ "$mismatches" -gt 0 ]; then
  echo "prove.sh: $mismatches outcome(s) differed from the expected" >&2
  exit 1
fi
echo "prove.sh: every outcome was the expected one; wrote $readme"
