#!/usr/bin/env bash
# Generates briefs/proof/2.7/README.md: the vendor evaluation walked through route files,
# upgrade, save as route, and re-link by `cargo run -p cairn-engine --example
# route_walkthrough -- fixtures` (version 1 exported and imported back byte for byte; the
# finished journey with two local edits upgraded to version 2, with the proposal's items, a
# conflict and its resolutions, a kept edit, an orphan, the preview, and the applied result;
# the journey saved as a route, created again, and re-linked), the upgrade at the limits, the
# brief's test suites, and the planted bug (a tombstoned node re-added on upgrade, caught by
# the tombstone scenario, then passing again once restored). Exits non-zero if any outcome
# differs from the one expected.
#
# usage: briefs/proof/2.7/prove.sh WORK_DIR
#
# WORK_DIR holds a copy of the tree for the planted bug; the repository itself is never
# modified, apart from the README this writes.
# shellcheck disable=SC2016 # backticks in single quotes are Markdown code spans
set -euo pipefail
repo=$(cd "$(dirname "$0")/../../.." && pwd)
work=${1:?usage: prove.sh WORK_DIR}
mkdir -p "$work"
work=$(cd "$work" && pwd)
readme=$repo/briefs/proof/2.7/README.md
export CARGO_TERM_COLOR=never MISE_TRUSTED_CONFIG_PATHS=$work/tree
mismatches=0
out=$readme.tmp
miss() {
  mismatches=$((mismatches + 1))
  echo "prove.sh: $1" >&2
}

cd "$repo"
cat >"$out" <<'EOF'
# Proof for brief 2.7: route files, upgrade, save as route, re-link, proposal documents

Generated by `briefs/proof/2.7/prove.sh WORK_DIR`; do not edit by hand. The script fails if
any outcome below differs from the one expected.

What this shows: a route version exports to a deterministic file and imports back to the
same graph, keys kept (A13); an upgrade is a three-way merge by key and local-edit markers
whose clean outcomes the upgrade mutation applies, with conflicts, kept edits, and orphans
as review items (B7); review items resolve into ordinary mutations, and only an unresolved
one blocks apply (C14, I6); a journey saves as a route with participation mapping and
exclusions (B8), and re-links to what it published, keeping differences as local edits (B9).
The sections are printed by `cargo run -p cairn-engine --example route_walkthrough --
fixtures`; every patch in them goes through `apply`.

EOF

status=0
walkthrough=$(mise exec -- cargo run --quiet --locked -p cairn-engine --all-features --example route_walkthrough -- fixtures 2>&1 | grep -v '^mbx') || status=$?
[ "$status" -eq 0 ] || miss "the walkthrough failed: $walkthrough"
printf '%s\n' "$walkthrough" >>"$out"
for expected in \
  '- Imported back, the graph equals the one exported: true.' \
  '- Exported again, byte-identical: true.' \
  'offers: keep the journey'"'"'s, take the route'"'"'s; chosen: none yet' \
  'kept local edit `{"node":{"node":"n_findings","edit":{"field":"estimate"}}}`' \
  '- orphan `n_workload`, keep: true; removing it removes `["n_workload_ingest","n_workload_query"]`' \
  '| `n_access` title | Access to the test environment | Environment and data access |' \
  '| `n_signoff` | absent | FromRoute, Todo |' \
  '| `n_workload` (orphan) | FromRoute, Done | Orphaned, Done |' \
  'every one equal by key to the original'"'"'s: true' \
  'markers `n_access` [{"field":"title"}]' \
  '- An upgrade to that version afterwards proposes 0 mutations and 0 items.'; do
  grep -qF -- "$expected" <<<"$walkthrough" || miss "the walkthrough does not show: $expected"
done

printf '\n## At the limits\n\n' >>"$out"
status=0
cost=$(mise exec -- cargo test --quiet --locked -p cairn-engine --all-features --test cost_upgrade -- --nocapture 2>&1) || status=$?
[ "$status" -eq 0 ] || miss "the cost test failed"
{
  printf 'A journey of 2,000 nodes (`generated::date_limits`, with its state) upgraded to a version that retitles every node: drafting (the merge, then a trial apply that validates and derives the candidate) and applying, beside an apply of a rename of the same journey for scale; and drafted against a version that keeps only the roots, so 1,999 nodes become orphans whose removals are computed in one pass. The merge itself is the difference between the applies; `crates/engine/src/upgrade/merge.rs` states its cost in operations. Elapsed time in a debug build, reported rather than gated:\n\n```\n'
  grep -E '^upgrade at the limits' <<<"$cost"
  printf '```\n'
} >>"$out"

printf '\n## The suites\n\n' >>"$out"
status=0
suites=$(mise exec -- cargo test --quiet --locked -p cairn-engine --all-features \
  --test format --test proposals --test upgrade --test save_relink --test property_upgrade \
  --test cost_upgrade 2>&1) || status=$?
[ "$status" -eq 0 ] || miss "the suites failed"
{
  printf 'The format round trips (every fixture route and generated graphs, byte for byte; import against a base), resolution of every item kind, every merge outcome and resolution of an upgrade, save as route and re-link, the property tests (an identical version proposes nothing, a kept upgrade applies exactly when it lists no violation and replays to its state, a saved journey is created again by key), and the cost test. In cargo'"'"'s order: `cost_upgrade.rs`, `format.rs`, `property_upgrade.rs`, `proposals.rs`, `save_relink.rs`, `upgrade.rs`:\n\n```\n'
  grep -E '^test result' <<<"$suites" | sed -E 's/; finished in .*//'
  printf '```\n'
} >>"$out"

printf '\n## Planted bug: a tombstoned node re-added on upgrade\n\n' >>"$out"
tree=$work/tree
rsync -a --delete --exclude target --exclude node_modules --exclude .jj --exclude .git "$repo/" "$tree/"
merge=$tree/crates/engine/src/upgrade/merge.rs
# A route node the journey no longer holds is added back instead of left out.
perl -0pi -e 's/            \(Some\(_\) \| None, None\) => \{\}\n/            (Some(targeted), None) => merger.add(&targeted.key, &present),\n            (None, None) => {}\n/' "$merge"
[ "$(grep -c 'Some(targeted), None) => merger.add' "$merge")" -eq 1 ] || miss "the planted bug did not apply"
status=0
planted_output=$(cd "$tree" && mise exec -- cargo test --quiet --all-features -p cairn-engine --test upgrade 2>&1) || status=$?
[ "$status" -ne 0 ] || miss "the planted bug went unnoticed"
grep -q "tombstoned_nodes_are_not_re_added" <<<"$planted_output" || miss "the tombstone scenario did not fail"
# cp, not rsync -a: a fresh mtime makes cargo rebuild the restored file.
cp "$repo/crates/engine/src/upgrade/merge.rs" "$merge"
status_after=0
after_output=$(cd "$tree" && mise exec -- cargo test --quiet --all-features -p cairn-engine --test upgrade 2>&1) || status_after=$?
[ "$status_after" -eq 0 ] || miss "the restored merge fails"
{
  printf 'In `crates/engine/src/upgrade/merge.rs` a base node the journey no longer holds (removed, so tombstoned) is added back from the target. `cargo test -p cairn-engine --test upgrade` exit status %s:\n\n```\n' "$status"
  grep -E "^thread '|code: [A-Za-z]+|^test result" <<<"$planted_output" | sed -E "s/ \\([0-9]+\\)//; s/; finished in .*//; s/^ +//" | awk '!seen[$0]++' | head -4
  printf '```\n\nRestored, exit status %s:\n\n```\n' "$status_after"
  grep -E '^test result' <<<"$after_output" | sed -E 's/; finished in .*//'
  printf '```\n'
} >>"$out"

mv "$out" "$readme"
if [ "$mismatches" -gt 0 ]; then
  echo "prove.sh: $mismatches outcome(s) differed from the expected" >&2
  exit 1
fi
echo "prove.sh: every outcome was the expected one; wrote $readme"
