#!/usr/bin/env bash
# Generates briefs/proof/2.3/README.md: the fixtures walked through derive's pass 4 (the
# vendor evaluation's due dates from its pinned decision meeting, checked against the table
# fixtures/README.md states; its bounds before and after the final report is pinned; the
# product launch's bounds before and after its code freeze is reached late, with the
# shortfall's chain; the report pinned past the meeting rejected with its chain, shortfall,
# and resolution moves), the cost test's operation counts at the limits, the native derive
# benchmark, the brief's test suites, and the planted bug (the containment constraint
# dropped, caught by the scenario asserting a child finishes before its parent's own work,
# then passing again once restored). Exits non-zero if any outcome differs from the one
# expected.
#
# usage: briefs/proof/2.3/prove.sh WORK_DIR
#
# WORK_DIR holds a copy of the tree for the planted bug; the repository itself is never
# modified, apart from the README this writes.
# shellcheck disable=SC2016 # backticks in single quotes are Markdown code spans
set -euo pipefail
repo=$(cd "$(dirname "$0")/../../.." && pwd)
work=${1:?usage: prove.sh WORK_DIR}
mkdir -p "$work"
work=$(cd "$work" && pwd)
readme=$repo/briefs/proof/2.3/README.md
export CARGO_TERM_COLOR=never MISE_TRUSTED_CONFIG_PATHS=$work/tree
mismatches=0
out=$readme.tmp
miss() {
  mismatches=$((mismatches + 1))
  echo "prove.sh: $1" >&2
}

cd "$repo"
cat >"$out" <<'EOF'
# Proof for brief 2.3: the date network

Generated by `briefs/proof/2.3/prove.sh WORK_DIR`; do not edit by hand. The script fails if
any outcome below differs from the one expected.

What this shows: every journey now has dates. `derive` builds one network of instants and
"B is at least k days after A" constraints from dependencies (inherited ones through
container entries), estimates, containment, date rules, and stage bounds, and solves it both
ways: earliest bounds forward from pins, actuals, and today; latest bounds backward from pins
and actuals. Each bound, slack, effective date, `overdue` flag, and shortfall comes with the
chain of constraints that produced it, ending at the pin, actual, or today that fixes it.
The plan layer (no actuals, no today) is an invariant: a patch that would leave a
contradictory chain is rejected with the chain, its sources, its pins, how many days it is
short, and the moves that would resolve it, each an ordinary mutation. Reality is never
rejected: a late actual is a shortfall on the derived dates. The tables below are printed by
`cargo run -p cairn-engine --example dates_walkthrough -- fixtures`.

EOF

status=0
walkthrough=$(mise exec -- cargo run --quiet --locked -p cairn-engine --example dates_walkthrough -- fixtures 2>&1 | grep -v '^mbx') || status=$?
[ "$status" -eq 0 ] || miss "the walkthrough failed: $walkthrough"
printf '%s\n' "$walkthrough" >>"$out"

# The due-date table is what fixtures/README.md states, row for row.
stated=0
while IFS= read -r line; do
  grep -qxF -- "$line" fixtures/README.md || miss "fixtures/README.md does not state: $line"
  stated=$((stated + 1))
done < <(awk '/^## Due dates from the pinned/ { p = 1 } /^## Before and after a pin/ { p = 0 } p && /^\|/' <<<"$walkthrough")
[ "$stated" -gt 2 ] || miss "no due-date rows were printed"
grep -q 'Short by \*\*5 days\*\*' <<<"$walkthrough" || miss "the late report pin is not short by 5 days"
grep -q 'Short by \*\*2 days\*\*' <<<"$walkthrough" || miss "the late code freeze is not short by 2 days"
printf '\nThe %s rows of the due-date table above are the ones `fixtures/README.md` states for the vendor evaluation; the J3 matrix entry "vendor evaluation: due dates from the pinned decision meeting" checks the same values.\n' "$stated" >>"$out"

printf '\n## The derive benchmark at the limits\n\nNative, optimized (`cargo run --release -p cairn-engine --example date_benchmark`), on the cost test'"'"'s graph; reported, not gated. The browser'"'"'s wasm half is brief 4.5'"'"'s.\n\n' >>"$out"
status=0
benchmark=$(mise exec -- cargo run --quiet --locked --release -p cairn-engine --example date_benchmark 2>&1 | grep -v '^mbx') || status=$?
[ "$status" -eq 0 ] || miss "the benchmark failed: $benchmark"
printf '%s\n' "$benchmark" >>"$out"

printf '\n## The suites\n\n' >>"$out"
status=0
suites=$(mise exec -- cargo test --quiet --locked -p cairn-engine --all-features \
  --test dates --test plan --test matrix --test property_dates --test cost_dates --lib 2>&1) || status=$?
[ "$status" -eq 0 ] || miss "the suites failed"
{
  printf 'The translation table row by row (the library'"'"'s unit tests), the execution layer and the plan layer by example, the J3 matrix with this brief'"'"'s entries, the property tests over generated dated journeys (among them the reference test of the entry chain against the plain expansion), and the cost test. In cargo'"'"'s order: the library, `cost_dates.rs`, `dates.rs`, `matrix.rs`, `plan.rs`, `property_dates.rs`:\n\n```\n'
  grep -E '^test result' <<<"$suites" | sed -E 's/; finished in .*//'
  printf '```\n'
} >>"$out"

printf '\n## Planted bug: containment no longer caps a child\n\n' >>"$out"
tree=$work/tree
rsync -a --delete --exclude target --exclude node_modules --exclude .jj --exclude .git "$repo/" "$tree/"
network=$tree/crates/engine/src/derive/dates/network.rs
perl -0pi -e 's/for edge in dependencies\.edges\(EdgeSet::Pruned\) \{/for edge in dependencies\n            .edges(EdgeSet::Pruned)\n            .filter(|edge| edge.source != EdgeSource::Containment)\n        {/' "$network"
cmp -s "$network" "$repo/crates/engine/src/derive/dates/network.rs" && miss "the containment constraint was not found"
status=0
planted_output=$(cd "$tree" && mise exec -- cargo test --quiet --all-features -p cairn-engine --test dates 2>&1) || status=$?
[ "$status" -ne 0 ] || miss "the planted bug went unnoticed"
grep -q "a_child_finishes_before_its_parents_own_work" <<<"$planted_output" \
  || miss "the scenario asserting a child finishes before its parent's own work did not fail"
# cp, not rsync -a: a fresh mtime makes cargo rebuild the restored file.
cp "$repo/crates/engine/src/derive/dates/network.rs" "$network"
status_after=0
after_output=$(cd "$tree" && mise exec -- cargo test --quiet --all-features -p cairn-engine --test dates 2>&1) || status_after=$?
[ "$status_after" -eq 0 ] || miss "the restored constraint fails"
{
  printf 'In `crates/engine/src/derive/dates/network.rs` the containment constraint (a parent'"'"'s own work starts after each child finishes) is left out of the network. `cargo test -p cairn-engine --test dates` exit status %s:\n\n```\n' "$status"
  grep -E "^thread 'a_child_finishes|^test result" <<<"$planted_output" | sed -E "s/ \\([0-9]+\\)//; s/; finished in .*//" | head -6
  printf '```\n\nRestored, exit status %s:\n\n```\n' "$status_after"
  grep -E '^test result' <<<"$after_output" | sed -E 's/; finished in .*//'
  printf '```\n'
} >>"$out"

mv "$out" "$readme"
if [ "$mismatches" -gt 0 ]; then
  echo "prove.sh: $mismatches outcome(s) differed from the expected" >&2
  exit 1
fi
echo "prove.sh: every outcome was the expected one; wrote $readme"
