#!/usr/bin/env bash
# Generates briefs/proof/4.3/README.md: an agent session through the MCP endpoint, recorded
# as the endpoint's own test drives it with rmcp's client in process
# (crates/api/tests/support/mcp.rs): the snapshot read first, the decisions needed listed
# with a filter, each answered, a patch refused with every violation, a breakdown proposed,
# reviewed, and applied, and the acting frontier after, which the test checks against the
# next list. Then the tool set's and the endpoint's test counts, and the planted bug
# (list_frontier without its paging, caught by the bounded-output test). Exits non-zero if
# any outcome differs from the one expected.
#
# usage: briefs/proof/4.3/prove.sh WORK_DIR
#
# WORK_DIR holds the transcripts and a copy of the tree for the planted bug; the repository
# itself is never modified, apart from the README this writes.
# shellcheck disable=SC2016 # backticks in single quotes are Markdown code spans
set -euo pipefail
repo=$(cd "$(dirname "$0")/../../.." && pwd)
work=${1:?usage: prove.sh WORK_DIR}
mkdir -p "$work"
work=$(cd "$work" && pwd)
readme=$repo/briefs/proof/4.3/README.md
export CARGO_TERM_COLOR=never MISE_TRUSTED_CONFIG_PATHS=$work/tree
mismatches=0
out=$readme.tmp
transcripts=$work/transcripts
rm -rf "$transcripts"
mkdir -p "$transcripts"
miss() {
  mismatches=$((mismatches + 1))
  echo "prove.sh: $1" >&2
}

cd "$repo"
cat >"$out" <<'EOF'
# Proof for brief 4.3: MCP server and shipped instructions

Generated by `briefs/proof/4.3/prove.sh WORK_DIR`; do not edit by hand. The script fails if
any outcome below differs from the one expected.

What this shows: an agent can now work a journey through Cairn's remote MCP endpoint
(Streamable HTTP at `/mcp`, behind the API's auth layer), with a curated tool set over the
service and the shipped instructions. When it connects, the server sends the guide
(`instructions/SKILL.md`) as its instructions and serves each workflow under
`instructions/workflows/` as a prompt; `instructions/` is also the skill as published.

The session below is the transcript of `crates/api/tests/mcp.rs`,
`an_agent_answers_the_decisions_and_breaks_down_the_placeholder`, the PRD's success
criterion as a script: an MCP client (rmcp's own) whose Streamable HTTP transport hands
each request to the API's router as served, over the memory store. Ann signs in with a test
provider that stands for any provider vouching for a verified email (`Bearer team-ann`);
her email is the vendor evaluation's lead's. Each step is the tool called with its
arguments and what came back: the tool's structured output, or, for a tool error, the
error the agent reads. Long results are cut after 40 lines. The proposal records its
author's user id, which is minted at random, so it differs from run to run.
EOF

# Runs one MCP test with its transcript on; appends the transcript under a heading.
section() {
  local title=$1 test=$2 note=$3 status=0
  mise exec -- env CAIRN_MCP_TRANSCRIPT="$transcripts" \
    cargo test --quiet --locked -p cairn-api --test mcp -- --exact "mcp_in_process::$test" \
    >"$work/mcp-$test.log" 2>&1 || status=$?
  local transcript=$transcripts/mcp_in_process__$test.md
  [ "$status" -eq 0 ] && [ -s "$transcript" ] || miss "mcp::$test failed or recorded nothing"
  {
    printf '\n## %s\n\n%s (`crates/api/tests/mcp.rs`, `%s`, exit status %s.)\n\n' "$title" "$note" "$test" "$status"
    cat "$transcript" 2>/dev/null || true
  } >>"$out"
}

section 'An agent session through the endpoint' an_agent_answers_the_decisions_and_breaks_down_the_placeholder \
  'I2, I3, I6, A15, B10, C10: the agent reads the snapshot first, lists the decisions it can answer now with the `decisions_needed` filter, and answers each in rank order with the vendor evaluation scenario'"'"'s answers, naming each write'"'"'s base revision and its own patch id. A patch with two mistakes (completing the placeholder before it is broken down, and a text answer to a yes-or-no decision) is refused with both violations and nothing written. It then proposes breaking the placeholder into two sub-deliverables under its own proposal id, reviews it (no violations, the frontier after), and applies it. The test checks that its acting frontier then equals the next list the service derives (2.6), and that no decision it could answer is left'

printf '\n## The tests\n\n' >>"$out"
status=0
tests=$(mise exec -- cargo test --locked -p cairn-mcp 2>&1) || status=$?
[ "$status" -eq 0 ] || miss "the tool set's tests failed"
status_mcp=0
endpoint=$(mise exec -- cargo test --locked -p cairn-api --test mcp 2>&1) || status_mcp=$?
[ "$status_mcp" -eq 0 ] || miss "the endpoint's tests failed"
{
  printf '`cargo test -p cairn-mcp` (rung 2), exit status %s, and `cargo test -p cairn-api --test mcp` (the `mcp_in_process` suite, rung 4), exit status %s:\n\n| Suite | Passed |\n|---|---|\n' "$status" "$status_mcp"
  awk '/^ *Running unittests/ { suite = $3 } /^ *Running tests\// { suite = $2 } /^ *Doc-tests/ { suite = "" }
       /^test result:/ && suite != "" { print "| `" suite "` | " $4 " |" }' <<<"$tests"$'\n'"$endpoint"
} >>"$out"
cat >>"$out" <<'EOF'

`tests/mcp.rs` calls every tool the endpoint lists at least once and checks each output
against its tool's output schema (`every_tool_answers_through_the_endpoint`), checks the
guide and prompts are served as the files say (`the_instructions_are_served`), that the
endpoint shares the API's auth (an anonymous call is challenged with the resource metadata,
an agent token acts as its agent for its user, both recorded), and that a host whose
capabilities leave MCP out serves no endpoint. `crates/mcp/tests/instructions.rs` checks
that every identifier the instructions write as code is a tool or a field or value some
tool takes or answers, and maps every I2 capability to its tools.
EOF

printf '\n## Planted bug: the frontier without its paging\n\n' >>"$out"
tree=$work/tree
rsync -a --delete --exclude target --exclude node_modules --exclude .jj --exclude .git "$repo/" "$tree/"
derived=$tree/crates/mcp/src/tools/derived.rs
perl -0pi -e 's/rows: page\(items, cursor\),/rows: Paged { total: u32::try_from(items.len()).unwrap_or(u32::MAX), next: None, items },/' "$derived"
cmp -s "$derived" "$repo/crates/mcp/src/tools/derived.rs" && miss "the planted bug was not planted"
bounded=(cargo test --locked -p cairn-mcp --test tools -- --exact the_frontier_is_paged_at_the_limit)
status=0
planted=$(cd "$tree" && mise exec -- "${bounded[@]}" 2>&1) || status=$?
[ "$status" -ne 0 ] || miss "the planted bug went unnoticed"
cp "$repo/crates/mcp/src/tools/derived.rs" "$derived"
status_after=0
after=$(cd "$tree" && mise exec -- "${bounded[@]}" 2>&1) || status_after=$?
[ "$status_after" -eq 0 ] || miss "the restored tree fails the bounded-output test"
{
  printf 'In `crates/mcp/src/tools/derived.rs`, `list_frontier` answers the whole acting frontier instead of a page of it (`rows: Paged { .., next: None, items }` for `rows: page(items, cursor)`). The bounded-output test, over a journey of 225 actions, exit status %s:\n\n```\n' "$status"
  grep -E 'panicked|assertion|left:|right:' <<<"$planted" | sed -E 's/ \([0-9]+\)//'
  printf '```\n\nRestored, exit status %s:\n\n```\n' "$status_after"
  grep -E '^test result' <<<"$after" | sed -E 's/; finished in .*//'
  printf '```\n'
} >>"$out"

mv "$out" "$readme"
if [ "$mismatches" -gt 0 ]; then
  echo "prove.sh: $mismatches outcome(s) differed from the expected" >&2
  exit 1
fi
echo "prove.sh: every outcome was the expected one; wrote $readme"
