#!/usr/bin/env bash
# Generates briefs/proof/2.6/README.md: the fixtures walked through the projections by
# `cargo run -p cairn-engine --example projection_walkthrough -- fixtures` (each fixture's
# visible set with actions hidden and its first three next items, checked against the lines
# fixtures/README.md states; the vendor evaluation at two zooms with roll-up badges, a trace,
# the decision view, the timeline, the status summary, the next list with filters, the agent
# snapshot with its top N and counts, a message draft, and a node's history), the projections
# at the limits, the brief's test suites, and the planted bug (edges collapsed onto the same
# pair of stand-ins without de-duplicating, caught by the C2 scenario, then passing again once
# restored). Exits non-zero if any outcome differs from the one expected.
#
# usage: briefs/proof/2.6/prove.sh WORK_DIR
#
# WORK_DIR holds a copy of the tree for the planted bug; the repository itself is never
# modified, apart from the README this writes.
# shellcheck disable=SC2016 # backticks in single quotes are Markdown code spans
set -euo pipefail
repo=$(cd "$(dirname "$0")/../../.." && pwd)
work=${1:?usage: prove.sh WORK_DIR}
mkdir -p "$work"
work=$(cd "$work" && pwd)
readme=$repo/briefs/proof/2.6/README.md
export CARGO_TERM_COLOR=never MISE_TRUSTED_CONFIG_PATHS=$work/tree
mismatches=0
out=$readme.tmp
miss() {
  mismatches=$((mismatches + 1))
  echo "prove.sh: $1" >&2
}

cd "$repo"
cat >"$out" <<'EOF'
# Proof for brief 2.6: projections

Generated by `briefs/proof/2.6/prove.sh WORK_DIR`; do not edit by hand. The script fails if
any outcome below differs from the one expected.

What this shows: every read view the PRD names is now a pure engine function over a derived
journey (`DerivedJourney`), with schema types in and out, so the browser and the server cut
the same views. The canvas level (C2) hides kinds, hoists what a hidden ancestor held, rolls
hidden nodes into their nearest visible ancestor, re-targets edges to visible stand-ins with
duplicates collapsed and self-edges dropped, marks blocked work whose prerequisite no drawn
edge stands for, and carries each container's badges; the trace (C7) runs over the full
structural graph; the decision view (C12), timeline (C13), status summary (C18), next list
(C10), list (C9), "mine" (E4), agent snapshot (I3), explanation pages, history (J4), and
message drafts (A10, G3) follow. Every derive below is at 2026-10-06, the scenario matrix's
clock, under the default rank constants. The sections are printed by
`cargo run -p cairn-engine --example projection_walkthrough -- fixtures`.

EOF

status=0
walkthrough=$(mise exec -- cargo run --quiet --locked -p cairn-engine --all-features --example projection_walkthrough -- fixtures 2>&1 | grep -v '^mbx') || status=$?
[ "$status" -eq 0 ] || miss "the walkthrough failed: $walkthrough"
printf '%s\n' "$walkthrough" >>"$out"

# The per-fixture lines are what fixtures/README.md states, line for line.
stated=0
while IFS= read -r line; do
  grep -qxF -- "$line" fixtures/README.md || miss "fixtures/README.md does not state: $line"
  stated=$((stated + 1))
done < <(grep -E '^- `[a-z-]+`, after step [0-9]+, ' <<<"$walkthrough")
[ "$stated" -eq 12 ] || miss "expected 12 per-fixture lines, printed $stated"
grep -qF '`n_reporting` to `n_final_review` (2 underlying)' <<<"$walkthrough" || miss "the two edges into the final review did not collapse into one"
grep -qF '`n_access` waits on `n_kickoff`' <<<"$walkthrough" || miss "the hoisted access does not carry the marker"
grep -qF 'after step 1: Hello, [missing: roles.eval_owner.name]' <<<"$walkthrough" || miss "the unfilled role is not marked"
printf '\nThe %s per-fixture lines above are the ones `fixtures/README.md` states; `crates/engine/tests/fixture_projections.rs` checks the same values.\n' "$stated" >>"$out"

printf '\n## At the limits\n\n' >>"$out"
status=0
cost=$(mise exec -- cargo test --quiet --locked -p cairn-engine --all-features --test cost_projections -- --nocapture 2>&1) || status=$?
[ "$status" -eq 0 ] || miss "the cost test failed"
{
  printf 'On `generated::date_limits` (2,000 nodes at the depth limit), every projection stays within its bound (a level within the canvas edges, each pair drawn once; pages within 200 items; explanation pages within 50). Elapsed time in a debug build, reported rather than gated; each module in `crates/engine/src/project/` states its cost in operations:\n\n```\n'
  grep -E '^projection at the limits' <<<"$cost"
  printf '```\n'
} >>"$out"

printf '\n## The suites\n\n' >>"$out"
status=0
suites=$(mise exec -- cargo test --quiet --locked -p cairn-engine --all-features \
  --test level --test trace --test lists --test snapshot --test history --test views \
  --test fixture_projections --test property_projections --test cost_projections 2>&1) || status=$?
[ "$status" -eq 0 ] || miss "the suites failed"
{
  printf 'The projections by example, on the fixtures and on hand-built journeys, the property tests (the level'"'"'s rules and monotonicity, traces consistent with the graph, the snapshot'"'"'s pages, counts, and agreement with the next list, history pages contiguous and complete), and the cost test. In cargo'"'"'s order: `cost_projections.rs`, `fixture_projections.rs`, `history.rs`, `level.rs`, `lists.rs`, `property_projections.rs`, `snapshot.rs`, `trace.rs`, `views.rs`:\n\n```\n'
  grep -E '^test result' <<<"$suites" | sed -E 's/; finished in .*//'
  printf '```\n'
} >>"$out"

printf '\n## Planted bug: edges collapsed without de-duplicating\n\n' >>"$out"
tree=$work/tree
rsync -a --delete --exclude target --exclude node_modules --exclude .jj --exclude .git "$repo/" "$tree/"
level=$tree/crates/engine/src/project/level.rs
# Each underlying edge becomes its own canvas edge, so two edges landing on the same pair of
# stand-ins are drawn twice.
perl -0pi -e '
  s/(        drawn\n            \.into_iter\(\)\n)(            \.map\(\|\(\(from, to\), underlying\)\| LevelEdge \{)/$1            .flat_map(|(ends, underlying)| underlying.into_iter().map(move |one| (ends, BTreeSet::from([one]))))\n$2/;
' "$level"
[ "$(grep -c 'flat_map(|(ends, underlying)|' "$level")" -eq 1 ] || miss "the planted bug did not apply"
status=0
planted_output=$(cd "$tree" && mise exec -- cargo test --quiet --all-features -p cairn-engine --test level 2>&1) || status=$?
[ "$status" -ne 0 ] || miss "the planted bug went unnoticed"
grep -q "edges_landing_on_the_same_pair_collapse_into_one" <<<"$planted_output" || miss "the collapse scenario did not fail"
# cp, not rsync -a: a fresh mtime makes cargo rebuild the restored file.
cp "$repo/crates/engine/src/project/level.rs" "$level"
status_after=0
after_output=$(cd "$tree" && mise exec -- cargo test --quiet --all-features -p cairn-engine --test level 2>&1) || status_after=$?
[ "$status_after" -eq 0 ] || miss "the restored projection fails"
{
  printf 'In `crates/engine/src/project/level.rs` each underlying edge is drawn as its own canvas edge instead of collapsing onto its pair of stand-ins. `cargo test -p cairn-engine --test level` exit status %s:\n\n```\n' "$status"
  grep -E "^thread '|^  left|^ right|^test result" <<<"$planted_output" | sed -E "s/ \\([0-9]+\\)//; s/; finished in .*//" | head -6
  printf '```\n\nRestored, exit status %s:\n\n```\n' "$status_after"
  grep -E '^test result' <<<"$after_output" | sed -E 's/; finished in .*//'
  printf '```\n'
} >>"$out"

mv "$out" "$readme"
if [ "$mismatches" -gt 0 ]; then
  echo "prove.sh: $mismatches outcome(s) differed from the expected" >&2
  exit 1
fi
echo "prove.sh: every outcome was the expected one; wrote $readme"
