#!/usr/bin/env bash
# Generates briefs/proof/5.1/: the README, a screenshot of each acceptance state of the node
# detail panel, and a short video of its main flow. Builds the module (mise run build:wasm)
# and the fixture server, runs the app's web unit tests (Vitest) and its browser tests for
# the panel (Playwright, e2e/detail.spec.ts in rung 6's web/app suite) keeping their counts,
# runs the proof's pictures (web/app/proof/detail.proof.ts), then the planted bug: derived
# dates shown without their chain, caught by the F7 unit test. The plant is made in place and
# always restored (checked byte for byte). Exits non-zero if any outcome differs from the one
# expected.
#
# usage: briefs/proof/5.1/prove.sh
# shellcheck disable=SC2016 # backticks in single quotes are Markdown code spans
set -euo pipefail
repo=$(cd "$(dirname "$0")/../../.." && pwd)
proof=$repo/briefs/proof/5.1
work=$repo/web/app/dist/prove-5.1
readme=$proof/README.md
export CARGO_TERM_COLOR=never
mismatches=0
miss() {
  mismatches=$((mismatches + 1))
  echo "prove.sh: $1" >&2
}
cd "$repo"
rm -rf "$work"
mkdir -p "$work"

mise run build:wasm
mise exec -- cargo build --quiet --locked -p cairn-wasm --example fixture_server

# The app's web unit tests: each file and its count.
unit=$work/vitest.json
(cd web/app && "$repo/node_modules/.bin/vitest" run --reporter=json --outputFile.json="$unit" >/dev/null) \
  || miss "the app's web unit tests failed"
unit_rows=$(node -e '
  const report = JSON.parse(require("fs").readFileSync(process.argv[1], "utf8"));
  for (const file of report.testResults) {
    const name = file.name.replace(/.*\/web\/app\//, "");
    if (!name.includes("/detail/") && !name.includes("markdown")) continue;
    const passed = file.assertionResults.filter((test) => test.status === "passed").length;
    console.log(`| \`${name}\` | ${passed} passed, ${file.assertionResults.length - passed} failed |`);
  }' "$unit")

# The panel's browser tests: each test and its outcome.
e2e=$work/playwright.json
(cd web/app && PLAYWRIGHT_JSON_OUTPUT_NAME=$e2e "$repo/node_modules/.bin/playwright" test e2e/detail.spec.ts --reporter=json >/dev/null) \
  || miss "the panel's browser tests failed"
e2e_rows=$(node -e '
  const report = JSON.parse(require("fs").readFileSync(process.argv[1], "utf8"));
  const walk = (suite) => [
    ...(suite.specs ?? []).map((spec) => `| ${spec.title} | ${spec.ok ? "passed" : "failed"} |`),
    ...(suite.suites ?? []).flatMap(walk),
  ];
  for (const suite of report.suites) for (const row of walk(suite)) console.log(row);
' "$e2e")

# The pictures.
pictures=(1-why-not-relevant 2-due-chain 3-why-blocked 4-gravity-contributors 5-participations
  6a-pin-rejected-with-chain 6b-resolved-by-a-move 7-note-added 8-link-added
  9-artifact-designated-and-completed 10-artifact-removed-stale 11-message-draft 12-dark-theme
  13-narrow-screen)
rm -f "$proof"/*.png "$proof"/*.webm
(cd web/app && CAIRN_PROOF_OUT=$proof "$repo/node_modules/.bin/playwright" test -c playwright.proof.config.ts proof/detail.proof.ts --reporter=line) \
  || miss "the proof run failed"
rm -rf "$proof/video"
for picture in "${pictures[@]}"; do
  [ -s "$proof/$picture.png" ] || miss "the picture $picture is missing"
done
[ -s "$proof/main-flow.webm" ] || miss "the main flow's video is missing"

# The planted bug, in place, restored on any exit: a derived date's chain left out.
dates=web/app/src/detail/DatesSection.tsx
cp "$dates" "$work/DatesSection.tsx"
restore() { cp "$work/DatesSection.tsx" "$repo/$dates"; }
trap restore EXIT
sed -i 's|        <ChainView view={view} chain={bound.chain} />|        {origin === "derived" ? null : <ChainView view={view} chain={bound.chain} />}|' "$dates"
cmp -s "$dates" "$work/DatesSection.tsx" && miss "the planted bug was not planted"
status=0
planted=$(cd web/app && "$repo/node_modules/.bin/vitest" run src/detail/DatesSection.test.tsx 2>&1) || status=$?
restore
trap - EXIT
cmp -s "$dates" "$work/DatesSection.tsx" || miss "DatesSection.tsx was not restored"
[ "$status" -ne 0 ] || miss "the planted bug went unnoticed"
caught=$(grep -E '(FAIL|AssertionError)' <<<"$planted" | sed 's/^ *//' | head -n 2 | paste -sd ' ' -)
[ -n "$caught" ] || miss "the planted bug's failure was not found"

out=$readme.tmp
{
  cat <<'EOF'
# Proof for brief 5.1: Node detail and explanations; notes, links, artifacts

Generated by `briefs/proof/5.1/prove.sh`; do not edit by hand. The script fails if any
outcome below differs from the one expected.

A journey's nodes now open into a detail panel (C8), beside the node list on a wide screen
and above it on a narrow one. Everything it explains comes from the journey's document as
derived in the tab's derive worker, so nothing is fetched to explain a value: why a node is
relevant or not and what decided it, what blocks it and through which ancestor, each date
told apart as pin, actual, or derived with the chain behind it and the pin or rule to edit
(F7), what makes up its gravity and leverage, and who participates and why. Every action is
one patch through the shell's write path, its rejection shown beside it: a pin that
contradicts the plan lists the chain and the moves that resolve it, and any one is sent with
the edit (F5); a milestone pinned by a decision is edited through that decision (E3); a
failed guard can be bypassed with a reason (D4). Notes and typed links are added, edited,
removed, and designated as the node's artifact (G1, G2); message drafts render with the
journey's context and copy (A10, G3); the node's history pages from the host (J4).

All pictures are on the in-browser host, seeded from the fixtures on each load.

## Explanations

Why a node is not relevant, and the ancestor whose condition decided it:

![Relevance and what produced it](1-why-not-relevant.png)

The final report's due date is its pin; its latest start is derived through its estimate,
from that pin. Each says what to edit to move it:

![The due chain](2-due-chain.png)

Why it is blocked: through the final review stage, which its opening holds back:

![Why blocked](3-why-blocked.png)

The bake-off's comparison: its gravity and the downstream nodes that make it up, and its
leverage split by owner (completing it frees work someone else owns):

![Gravity contributors](4-gravity-contributors.png)

Its participations, each with where it comes from (a role, an ancestor, the default owner):

![Participations](5-participations.png)

## A pin that contradicts the plan, resolved inline (F5)

Pinning the final report after the decision meeting it must finish before is rejected with
the contradictory chain and the moves that each give it the days it lacks:

![The rejection and its moves](6a-pin-rejected-with-chain.png)

Choosing "move the pin earlier" sends the edit with that move as one patch:

![Resolved](6b-resolved-by-a-move.png)

## Notes, links, and artifacts (G1, G2, D4)

A note, in markdown, attributed and timestamped:

![A note](7-note-added.png)

A reference link on the documentation deliverable, which requires an artifact:

![A link](8-link-added.png)

The link designated as the artifact, and the deliverable completed:

![Designated and completed](9-artifact-designated-and-completed.png)

The artifact removed after completion: the deliverable stays done and is `stale` with
"missing artifact", and the notice names what the patch newly caused (D7):

![Removed and stale](10-artifact-removed-stale.png)

## A message draft (A10, G3)

The access request rendered with the journey's name, the evaluation owner's name, and the
purpose answer, ready to copy:

![A message draft](11-message-draft.png)

## Themes and a narrow screen

![Dark theme](12-dark-theme.png)

![A narrow screen](13-narrow-screen.png)

The main flow: the final report's due chain, a later pin rejected and resolved with a move,
and an artifact designated and completed: [main-flow.webm](main-flow.webm).

## The tests

The app's web unit tests for the panel (Vitest, rung 6):

| File | Result |
|---|---|
EOF
  printf '%s\n' "$unit_rows"
  cat <<'EOF'

The panel's browser tests (Playwright in Chromium, rung 6, `web/app/e2e/detail.spec.ts`):

| Test | Result |
|---|---|
EOF
  printf '%s\n' "$e2e_rows"
  cat <<'EOF'

## The planted bug

Derived dates shown without their chain (the panel keeps the chain only for pins and
actuals): F7's unit test "shows a derived date with its chain" fails:

```text
EOF
  printf '%s\n' "$caught"
  echo '```'
} >"$out"
mv "$out" "$readme"
if [ "$mismatches" -ne 0 ]; then
  echo "prove.sh: $mismatches outcomes differ from those expected" >&2
  exit 1
fi
echo "prove.sh: wrote $readme"
