#!/usr/bin/env bash
# Generates briefs/proof/4.2/README.md: real requests and responses, recorded as the API's
# own tests send them to a server on loopback (crates/api/tests/support/transcript.rs) and
# written as the curl commands that would send them: a journey created and patched, a
# patch resubmitted after a lost response, a three-violation rejection, a conflict and the
# Rust client's safe retry, an overlapping conflict surfaced, the SSE stream from current
# revisions to a tick, the domain document, and capabilities; then the API's test count
# per suite, and the planted bug (a response type changed without regenerating, caught by
# rung 5). Exits non-zero if any outcome differs from the one expected.
#
# usage: briefs/proof/4.2/prove.sh WORK_DIR
#
# WORK_DIR holds the transcripts and a copy of the tree for the planted bug; the repository
# itself is never modified, apart from the README this writes. Needs `npm ci` first.
# shellcheck disable=SC2016 # backticks in single quotes are Markdown code spans
set -euo pipefail
repo=$(cd "$(dirname "$0")/../../.." && pwd)
work=${1:?usage: prove.sh WORK_DIR}
mkdir -p "$work"
work=$(cd "$work" && pwd)
readme=$repo/briefs/proof/4.2/README.md
export CARGO_TERM_COLOR=never MISE_TRUSTED_CONFIG_PATHS=$work/tree
mismatches=0
out=$readme.tmp
transcripts=$work/transcripts
rm -rf "$transcripts"
mkdir -p "$transcripts"
miss() {
  mismatches=$((mismatches + 1))
  echo "prove.sh: $1" >&2
}

cd "$repo"
cat >"$out" <<'EOF'
# Proof for brief 4.2: HTTP API, OpenAPI, SSE, TypeScript client

Generated by `briefs/proof/4.2/prove.sh WORK_DIR`; do not edit by hand. The script fails if
any outcome below differs from the one expected.

What this shows: everything the service offers is now an HTTP endpoint behind the auth
layer, described by a generated OpenAPI document (`openapi/cairn.json`) from which the
TypeScript client's types are generated (`web/client/generated/`). Each section is the
transcript of one of `crates/api`'s own tests, recorded as it ran against a server on
loopback over the memory store: the request as the curl command that would send it, and
the response. Ann and Bob sign in with a test provider that stands for any provider
vouching for a verified email (`Bearer team-<name>`); Ann's email is the vendor
evaluation's lead's, so she is that entity. Request ids are masked (`rq_…`), long bodies
cut, and the route the vendor evaluation follows is published before each test, not shown.
EOF

# Runs one test with its transcript on; appends the transcript under a heading.
section() {
  local title=$1 suite=$2 test=$3 note=$4 status=0
  mise exec -- env CAIRN_API_TRANSCRIPT="$transcripts" \
    cargo test --quiet --locked -p cairn-api --test "$suite" -- --exact "in_process::$test" \
    >"$work/$suite-$test.log" 2>&1 || status=$?
  local transcript=$transcripts/in_process__$test.md
  [ "$status" -eq 0 ] && [ -s "$transcript" ] || miss "$suite::$test failed or recorded nothing"
  {
    printf '\n## %s\n\n%s (`tests/%s.rs`, `%s`, exit status %s.)\n\n' "$title" "$note" "$suite" "$test" "$status"
    cat "$transcript" 2>/dev/null || true
  } >>"$out"
}

section 'A journey created, patched, and a lost response resubmitted' http a_patch_lands_once_and_its_resubmission_is_answered_from_its_receipt \
  'A17, H5: the scenario'"'"'s first step creates the journey at base revision 0; a note lands at revision 2; sent again, it is answered from its receipt; its id with other content is refused 409.'
section 'Three violations arrive as three' http three_violations_arrive_as_three \
  'A15: a patch with three independent violations is answered 422 with every one, by path, as the engine listed them.'
section 'A conflict, and the client'"'"'s safe retry' client a_non_overlapping_conflict_is_retried_on_its_own \
  'H5: Ann'"'"'s note is stale after Bob'"'"'s; the 409 carries what intervened, which cannot overlap her note, so the Rust client resubmits it at the revision the rejection reports. Then her client resends it, as after a lost response, and it is answered from its receipt.'
section 'An overlapping conflict is surfaced' client an_overlapping_conflict_is_surfaced \
  'H5: Ann'"'"'s removal of a group was drafted before Bob renamed the action inside it; what intervened overlaps the removal, so the client surfaces the 409 rather than resubmitting.'
section 'The SSE stream: current revisions, then a tick' stream a_stream_starts_from_current_revisions_then_ticks \
  'H6: Ann watches the journey, the deployment, and a journey that does not exist.'
section 'The domain document' reads a_document_derives_to_what_the_server_derives \
  'The journey'"'"'s stored graph and state, the derive inputs at the caller'"'"'s today in the deployment'"'"'s zone (Etc/GMT+5: 2026-10-06T03:00Z is still the 5th there) with her entity as the viewer, and the engine version; nothing derived. The test derives it with the engine and gets what the server derives at the same inputs.'
section 'Capabilities and the other reads' reads every_read_answers_what_the_service_holds \
  'Every store-backed read answers what the service holds, and capabilities what the host offers.'

printf '\n## The API'"'"'s tests\n\n' >>"$out"
status=0
tests=$(mise exec -- cargo test --locked -p cairn-api 2>&1) || status=$?
[ "$status" -eq 0 ] || miss "the API's tests failed"
{
  printf '`cargo test -p cairn-api` (unit tests in rung 2, the `in_process` suites in rung 4), exit status %s:\n\n| Suite | Passed |\n|---|---|\n' "$status"
  awk '/^ *Running unittests/ { suite = $3 } /^ *Running tests\// { suite = $2 } /^ *Doc-tests/ { suite = "" }
       /^test result:/ && suite != "" { print "| `" suite "` | " $4 " |" }' <<<"$tests"
} >>"$out"

printf '\n## Planted bug: a response type changed without regenerating\n\n' >>"$out"
tree=$work/tree
rsync -a --delete --exclude target --exclude node_modules --exclude .jj --exclude .git "$repo/" "$tree/"
ln -sfn "$repo/node_modules" "$tree/node_modules"
wire=$tree/crates/api/src/wire/mod.rs
perl -0pi -e 's/    pub sse: bool,/    pub sse: bool,\n    \/\/\/ Planted: a field the generated artifacts do not have.\n    pub planted: bool,/; s/            sse: \*sse,/            sse: *sse,\n            planted: false,/' "$wire"
cmp -s "$wire" "$repo/crates/api/src/wire/mod.rs" && miss "the planted bug was not planted"
status=0
planted=$(cd "$tree" && mise exec -- mise run check:5 2>&1) || status=$?
[ "$status" -ne 0 ] || miss "the planted bug went unnoticed"
# Rung 5 regenerated the planted outputs in the copy; restore them with the source.
cp "$repo/crates/api/src/wire/mod.rs" "$wire"
rsync -a --delete "$repo/openapi/" "$tree/openapi/"
rsync -a --delete "$repo/web/client/generated/" "$tree/web/client/generated/"
status_after=0
after=$(cd "$tree" && mise exec -- mise run check:5 2>&1) || status_after=$?
[ "$status_after" -eq 0 ] || miss "the restored tree fails rung 5"
{
  printf 'In `crates/api/src/wire/mod.rs`, the capabilities document gains a field and `mise run gen` is not run, so `openapi/` and `web/client/generated/` no longer match their source. `mise run check:5` exit status %s:\n\n```\n' "$status"
  grep -E '^[<>] |ladder: rung 5' <<<"$planted" | sed -E 's/^([<>]) [0-9a-f]{64}/\1 <sha256>/'
  printf '```\n\nRestored, exit status %s:\n\n```\n' "$status_after"
  grep -E 'ladder: rung 5' <<<"$after"
  printf '```\n'
} >>"$out"

mv "$out" "$readme"
if [ "$mismatches" -gt 0 ]; then
  echo "prove.sh: $mismatches outcome(s) differed from the expected" >&2
  exit 1
fi
echo "prove.sh: every outcome was the expected one; wrote $readme"
