#!/usr/bin/env bash
# Generates briefs/proof/4.9/README.md: real requests and responses, recorded as the API's
# own tests send them to a server on loopback (crates/api/tests/support/transcript.rs) and
# written as the curl commands that would send them: the vendor evaluation's next list,
# snapshot, and other projections; node detail with its explanation list capped and paged;
# a proposal created by an agent, edited, previewed, and applied by a reviewer; a create
# resubmitted by id; an apply against a moved journey, stale until refreshed; an upgrade
# proposal with its review items; and a route version exported and imported back. Then the
# API's test count per suite, and the planted bug (node detail without its explanation cap,
# caught by the size-budget test). Exits non-zero if any outcome differs from the one
# expected.
#
# usage: briefs/proof/4.9/prove.sh WORK_DIR
#
# WORK_DIR holds the transcripts and a copy of the tree for the planted bug; the repository
# itself is never modified, apart from the README this writes.
# shellcheck disable=SC2016 # backticks in single quotes are Markdown code spans
set -euo pipefail
repo=$(cd "$(dirname "$0")/../../.." && pwd)
work=${1:?usage: prove.sh WORK_DIR}
mkdir -p "$work"
work=$(cd "$work" && pwd)
readme=$repo/briefs/proof/4.9/README.md
export CARGO_TERM_COLOR=never MISE_TRUSTED_CONFIG_PATHS=$work/tree
mismatches=0
out=$readme.tmp
transcripts=$work/transcripts
rm -rf "$transcripts"
mkdir -p "$transcripts"
miss() {
  mismatches=$((mismatches + 1))
  echo "prove.sh: $1" >&2
}

cd "$repo"
cat >"$out" <<'EOF'
# Proof for brief 4.9: HTTP API completion

Generated by `briefs/proof/4.9/prove.sh WORK_DIR`; do not edit by hand. The script fails if
any outcome below differs from the one expected.

What this shows: every operation the service offers is now an HTTP endpoint behind the auth
layer (I1: `crates/api/tests/openapi.rs` checks each service method against the endpoint
table, with nothing awaiting): every projection of a journey, node detail with capped and
pageable explanations, proposals created under client ids and reviewed, upgrades, saves as
route, and re-links drafted as proposals, and route files exported and imported. The OpenAPI
document (`openapi/cairn.json`) and the TypeScript types (`web/client/generated/`) are
regenerated from the same Rust types. Each section is the transcript of one of
`crates/api`'s own tests, recorded as it ran against a server on loopback over the memory
store: the request as the curl command that would send it, and the response. Ann and Bob
sign in with a test provider that stands for any provider vouching for a verified email
(`Bearer team-<name>`); Ann's email is the vendor evaluation's lead's, so she is that
entity. Request ids are masked (`rq_…`), agent tokens cut short, long bodies cut after 60
lines, and set-up not shown is noted in italics. User and agent ids are minted at random, so
they differ from run to run; everything else reads the same.
EOF

# Runs one test with its transcript on; appends the transcript under a heading.
section() {
  local title=$1 suite=$2 test=$3 note=$4 status=0
  mise exec -- env CAIRN_API_TRANSCRIPT="$transcripts" \
    cargo test --quiet --locked -p cairn-api --test "$suite" -- --exact "in_process::$test" \
    >"$work/$suite-$test.log" 2>&1 || status=$?
  local transcript=$transcripts/in_process__$test.md
  [ "$status" -eq 0 ] && [ -s "$transcript" ] || miss "$suite::$test failed or recorded nothing"
  {
    printf '\n## %s\n\n%s (`tests/%s.rs`, `%s`, exit status %s.)\n\n' "$title" "$note" "$suite" "$test" "$status"
    cat "$transcript" 2>/dev/null || true
  } >>"$out"
}

section 'The next list, the snapshot, and the other projections' projections every_projection_answers_what_the_service_derives \
  'I1, I3, C10: the vendor evaluation after kickoff, read by Ann on 2026-10-06. Each projection carries the journey and deployment revisions and the today it was derived from; the test checks each against the service'"'"'s own answer. The next list ranks `n_access`, `n_decision_meeting`, `n_workload` (fixtures/README.md); the snapshot is scoped to the setup stage at depth 1.'
section 'Node detail with its explanations capped and paged' projections node_detail_caps_its_explanations_and_the_rest_page \
  'C8; ARCHITECTURE, HTTP API: Size budgets. `n_root` has 103 nodes downstream, so its gravity has 103 contributors: node detail carries the largest 50 (`explanation_entry_count_max`) and the total, and the explanation pages continue the list from its cursor, with the revision the cursor belongs to, every entry once.'
section 'A proposal created by an agent, edited, previewed, and applied' proposals a_reviewer_applies_a_proposal_and_is_recorded_as_confirming_it \
  'I6, H2, C14: an agent token of Ann'"'"'s creates `pr_note` under its own id and edits it to revision 2; the journey stays at revision 3. Bob previews it, applies the revision he reviewed (an older one is stale), and every event of the apply records him as the confirming user. Resubmitted after a lost response, the apply is answered from its receipt.'
section 'A proposal resubmitted by id is fetched, not duplicated' proposals a_proposal_resubmitted_by_id_is_fetched_not_duplicated \
  'I6, H5: the agent, having lost a response, creates `pr_note` again under a new patch id and is answered the proposal it holds; under the same patch id, the receipt; an edit at an old revision is stale.'
section 'An apply against a moved journey, stale until refreshed' proposals an_apply_against_a_moved_journey_is_stale_until_refreshed \
  'I6: the journey moves after `pr_note` was drafted; the preview names what moved, the apply is refused 409 with the intervening touched set, and once refreshed (revision 2, drafted against journey revision 4) and previewed again it applies.'
section 'An upgrade proposal with its review items' routes an_upgrade_is_a_proposal_whose_conflict_blocks_until_resolved \
  'B7, C14, I6, Journey durability: the upgrade to version 2 is drafted as a proposal whose items are a conflict (the retitled `n_access`), kept local edits, and an orphan; the journey stays on version 1. Its apply is refused while the conflict needs a choice; resolved to the route'"'"'s side, previewed clean, it applies and the journey follows version 2.'
section 'A route version exported and imported back' routes an_export_imports_back_as_a_new_draft \
  'A13: version 1 exported names the version it extends; imported back it opens a draft whose export is the same file; resubmitted under the same patch id it is answered from its receipt.'

printf '\n## The API'"'"'s tests\n\n' >>"$out"
status=0
tests=$(mise exec -- cargo test --locked -p cairn-api 2>&1) || status=$?
[ "$status" -eq 0 ] || miss "the API's tests failed"
{
  printf '`cargo test -p cairn-api` (unit tests in rung 2, the `in_process` suites in rung 4), exit status %s:\n\n| Suite | Passed |\n|---|---|\n' "$status"
  awk '/^ *Running unittests/ { suite = $3 } /^ *Running tests\// { suite = $2 } /^ *Doc-tests/ { suite = "" }
       /^test result:/ && suite != "" { print "| `" suite "` | " $4 " |" }' <<<"$tests"
} >>"$out"

printf '\n## Planted bug: node detail without its explanation cap\n\n' >>"$out"
tree=$work/tree
rsync -a --delete --exclude target --exclude node_modules --exclude .jj --exclude .git "$repo/" "$tree/"
project=$tree/crates/engine/src/derive/project.rs
perl -pi -e 's/let cut = complete\.for_response\(\);/let cut = complete;/' "$project"
cmp -s "$project" "$repo/crates/engine/src/derive/project.rs" && miss "the planted bug was not planted"
size_budget=(cargo test --locked -p cairn-api --test projections -- --exact in_process::node_detail_caps_its_explanations_and_the_rest_page)
status=0
planted=$(cd "$tree" && mise exec -- "${size_budget[@]}" 2>&1) || status=$?
[ "$status" -ne 0 ] || miss "the planted bug went unnoticed"
cp "$repo/crates/engine/src/derive/project.rs" "$project"
status_after=0
after=$(cd "$tree" && mise exec -- "${size_budget[@]}" 2>&1) || status_after=$?
[ "$status_after" -eq 0 ] || miss "the restored tree fails the size-budget test"
{
  printf 'In `crates/engine/src/derive/project.rs`, the explanation list is no longer cut to the response limit (`let cut = complete;` for `complete.for_response()`), so node detail carries every contributor. The size-budget test, exit status %s:\n\n```\n' "$status"
  grep -E 'panicked|assertion|left:|right:' <<<"$planted" | sed -E 's/ \([0-9]+\)//'
  printf '```\n\nRestored, exit status %s:\n\n```\n' "$status_after"
  grep -E '^test result' <<<"$after" | sed -E 's/; finished in .*//'
  printf '```\n'
} >>"$out"

mv "$out" "$readme"
if [ "$mismatches" -gt 0 ]; then
  echo "prove.sh: $mismatches outcome(s) differed from the expected" >&2
  exit 1
fi
echo "prove.sh: every outcome was the expected one; wrote $readme"
