#!/usr/bin/env bash
# Generates briefs/proof/4.8/README.md: through the service, over the memory store and a Turso
# file (`cargo run -p cairn-service --example completion_proof`), the vendor evaluation's
# ranked next list and snapshot; a proposal created by an agent, edited, previewed with its
# consequences, and applied by a reviewer recorded as confirming it; an upgrade to version 2
# with its review items resolved; and version 2 exported and imported back as a new draft;
# then the service's test suites with their counts, and the planted bug (the confirming user
# never stamped on a proposal apply, caught by the H2 test, then passing again once
# restored). Exits non-zero if any outcome differs from the one expected.
#
# usage: briefs/proof/4.8/prove.sh WORK_DIR
#
# WORK_DIR holds the proof's Turso file and a copy of the tree for the planted bug; the
# repository itself is never modified, apart from the README this writes.
# shellcheck disable=SC2016 # backticks in single quotes are Markdown code spans
set -euo pipefail
repo=$(cd "$(dirname "$0")/../../.." && pwd)
work=${1:?usage: prove.sh WORK_DIR}
mkdir -p "$work"
work=$(cd "$work" && pwd)
tree=$work/tree
readme=$repo/briefs/proof/4.8/README.md
export CARGO_TERM_COLOR=never MISE_TRUSTED_CONFIG_PATHS=$tree
mismatches=0
out=$readme.tmp
miss() {
  mismatches=$((mismatches + 1))
  echo "prove.sh: $1" >&2
}

cd "$repo"
cat >"$out" <<'HEADER'
# Proof for brief 4.8: service completion

Generated by `briefs/proof/4.8/prove.sh WORK_DIR`; do not edit by hand. The script fails if
any outcome below differs from the one expected.

What this shows: a host can now ask the service for every derived view of a journey (ranked
next lists, snapshots, and the other projections, memoized invisibly), run proposals as
first-class records (created by an agent with its own id, edited against their own revision,
previewed with what they would cause, and applied by someone recorded as confirming them),
take a journey to a new route version only through such a proposal, and move routes in and
out as files. Everything below goes through `cairn_service::Service`, printed by `cargo run
-p cairn-service --example completion_proof`, once over the memory store and once over a
Turso file.

HEADER

db=$work/proof.db
rm -f "$db" "$db"-*
status=0
mise exec -- cargo run --quiet --locked -p cairn-service --example completion_proof -- "$db" >"$work/walk.md" 2>"$work/walk.err" || status=$?
[ "$status" -eq 0 ] || { cat "$work/walk.err" >&2; miss "the walkthrough failed"; }
cat "$work/walk.md" >>"$out"
grep -q 'the same way: \*\*yes\*\*' "$work/walk.md" || miss "the two stores answered differently"
grep -q '| `"proposal_applied"` | `u_lead` | `ag_helper` | `u_reviewer` |' "$work/walk.md" || miss "the confirming user was not recorded"
grep -q '| lineage | vendor-evaluation version 1 | vendor-evaluation version 2 |' "$work/walk.md" || miss "the upgrade did not apply"
grep -q 'every node matched by path: true' "$work/walk.md" || miss "the import did not match by path"

printf '## The suites\n\n' >>"$out"
status=0
tests=$(mise exec -- cargo test --locked -p cairn-service --all-features 2>&1) || status=$?
[ "$status" -eq 0 ] || miss "the service's tests failed"
{
  printf 'The service'"'"'s tests (`cargo test -p cairn-service`; the read, proposal, and route cases run once over each store), exit status %s:\n\n```\n' "$status"
  grep -E '^ *Running |^test result' <<<"$tests" | sed -E 's/ \(target[^)]*\)//; s/; finished in [0-9.]+s//'
  printf '```\n\n'
} >>"$out"

printf '## The planted bug\n\n' >>"$out"
rsync -a --delete --exclude target --exclude node_modules --exclude .jj --exclude .git "$repo/" "$tree/"
pipeline=$tree/crates/engine/src/pipeline.rs
perl -0pi -e 's/confirming_user = Some\(inputs\.actor\.user\.clone\(\)\);/let _ = &inputs.actor.user;/' "$pipeline"
cmp -s "$pipeline" "$repo/crates/engine/src/pipeline.rs" && miss "the planted bug was not planted"
case_name=memory::a_proposal_is_previewed_and_applied_with_its_confirming_user
status=0
planted=$(cd "$tree" && mise exec -- cargo test --quiet --locked -p cairn-service --test proposals -- "$case_name" 2>&1) || status=$?
[ "$status" -ne 0 ] || miss "the planted bug went unnoticed"
# cp, not rsync -a: a fresh mtime makes cargo rebuild the restored file.
cp "$repo/crates/engine/src/pipeline.rs" "$pipeline"
status_after=0
after=$(cd "$tree" && mise exec -- cargo test --quiet --locked -p cairn-service --test proposals -- "$case_name" 2>&1) || status_after=$?
[ "$status_after" -eq 0 ] || miss "the restored service fails"
{
  printf 'In `crates/engine/src/pipeline.rs`, a proposal apply'"'"'s events never record the user applying it as the confirming user (H2). `%s` exit status %s:\n\n```\n' "$case_name" "$status"
  grep -E 'panicked|^ *left|^ *right|^test result' <<<"$planted" | sed -E 's/ \([0-9]+\)//; s/; finished in [0-9.]+s//' | head -4
  printf '```\n\nRestored, exit status %s:\n\n```\n' "$status_after"
  grep -E '^test result' <<<"$after" | sed -E 's/; finished in [0-9.]+s//'
  printf '```\n'
} >>"$out"

mv "$out" "$readme"
if [ "$mismatches" -gt 0 ]; then
  echo "prove.sh: $mismatches outcome(s) differed from the expected" >&2
  exit 1
fi
echo "prove.sh: every outcome was the expected one; wrote $readme"
