#!/usr/bin/env bash
# Generates briefs/proof/3.2/README.md: the requests and responses of the auth crate's own
# tests, recorded as they run (tests/support/transcript.rs) on a bare axum router: a
# sign-in through each provider and the identity it produced, an MCP client's whole OAuth
# flow ending in an agent token, a token minted then used then revoked, and the refusals
# (off loopback, a failing credential, spoiled ID tokens, a callback in another browser);
# then the crate's test count per suite and the planted bug (the audience check skipped,
# caught by the spoiled-token test). Exits non-zero if any outcome differs from the one
# expected.
#
# usage: briefs/proof/3.2/prove.sh WORK_DIR
#
# WORK_DIR holds the transcripts and a copy of the tree for the planted bug; the repository
# itself is never modified, apart from the README this writes.
# shellcheck disable=SC2016 # backticks in single quotes are Markdown code spans
set -euo pipefail
repo=$(cd "$(dirname "$0")/../../.." && pwd)
work=${1:?usage: prove.sh WORK_DIR}
mkdir -p "$work"
work=$(cd "$work" && pwd)
readme=$repo/briefs/proof/3.2/README.md
export CARGO_TERM_COLOR=never MISE_TRUSTED_CONFIG_PATHS=$work/tree
mismatches=0
out=$readme.tmp
transcripts=$work/transcripts
rm -rf "$transcripts"
mkdir -p "$transcripts"

cd "$repo"
cat >"$out" <<'EOF'
# Proof for brief 3.2: auth providers, users, identities, agent tokens

Generated by `briefs/proof/3.2/prove.sh WORK_DIR`; do not edit by hand. The script fails if
any outcome below differs from the one expected.

What this shows: every provider signs someone in, and what each refuses it refuses. Each
section is the transcript of one of `crates/auth`'s own tests, recorded as it ran: the
requests it sent through `Auth::protect` and `Auth::router` on a bare axum router (the
stand-in for 4.2's API, with `/whoami` answering the actor the layer produced), the
responses, and the records the test then read from the store. Everything is offline: OIDC
runs against a stub issuer on loopback with a key generated for the test, Tailscale's
direct mode against a fake tailscaled on a unix socket. Secrets are cut short (`…`); the
store keeps only their SHA-256 digests.
EOF

# Runs one test with its transcript on; appends the transcript under a heading.
section() {
  local title=$1 suite=$2 test=$3 note=$4 status=0
  mise exec -- env CAIRN_AUTH_TRANSCRIPT="$transcripts" \
    cargo test --quiet --locked -p cairn-auth --test "$suite" -- --exact "$suite::$test" \
    >"$work/$suite-$test.log" 2>&1 || status=$?
  local transcript=$transcripts/${suite}__$test.md
  if [ "$status" -ne 0 ] || [ ! -s "$transcript" ]; then
    mismatches=$((mismatches + 1))
    echo "prove.sh: $suite::$test failed or recorded nothing" >&2
  fi
  {
    printf '\n## %s\n\n%s (`%s::%s`, exit status %s.)\n\n' "$title" "$note" "$suite" "$test" "$status"
    cat "$transcript" 2>/dev/null || true
  } >>"$out"
}

section 'Dev: the named dev user' layer the_named_dev_user_is_one_user_created_once \
  'H1, local mode: every request from this machine is the dev user, created on the first request and logged; the second request finds the same user.'
section 'Dev: refused off loopback without the override' layer dev_mode_is_refused_off_loopback_without_the_override \
  'The dev provider will not start on a listener other machines reach; with the override it serves another machine; without it, a request from another machine is refused.'
section 'Dev: the static token' layer the_dev_token_signs_in_and_a_wrong_or_unclaimed_token_is_refused \
  'The token signs in; a wrong token, and a token shaped like one of Cairn'"'"'s own that no provider claims, are refused with `invalid_token`; no credential asks for one.'
section 'A failing credential never falls through' layer a_refused_credential_does_not_fall_through_to_another_provider \
  'The token provider is listed before a provider that signs every local request in; a wrong token, or an `Authorization` header no provider reads, is refused all the same.'
section 'OIDC: a sign-in and the identity it produced' oidc a_sign_in_ends_in_a_session_for_the_identity_the_issuer_names \
  'H1: the sign-in sends the browser to the issuer with PKCE (S256), a state, and a nonce; the callback exchanges the code and verifies the ID token, then starts a session. The identity holds the email the issuer marked verified (H3), lower-cased.'
section 'OIDC: spoiled ID tokens' oidc a_spoiled_id_token_is_refused \
  'An ID token with the wrong issuer, the wrong audience, expired, signed by another key, or carrying another nonce is refused, and no session or user is created.'
section 'OIDC: the state is bound to the browser' oidc the_state_and_verifier_are_bound_to_the_browser_that_started \
  'A callback without the sign-in cookie, or with another sign-in'"'"'s, is refused; a state is used once.'
section 'Built-in OAuth: an MCP client from a 401 to an agent token' oauth an_mcp_client_discovers_registers_and_gets_an_agent_token \
  'I2: the 401 names the resource metadata, which names the authorization server; the client registers (public, loopback redirect), sends the user to authorize; the browser has no session, so it signs in through OIDC and comes back; the user allows the client, the code goes to the registered redirect URI, and the token endpoint exchanges it, with the PKCE verifier, for an agent token acting for the user (H2).'
section 'An agent token: minted, used, revoked' tokens a_token_is_minted_then_used_then_revoked \
  'H2: the token is shown once and the store holds only its digest; it signs requests in as an agent acting for its user until revoked; both operations are logged.'
section 'Tailscale direct: whois' tailscale direct_mode_asks_tailscaled_who_the_peer_is \
  'The listener is on a tailnet address; tailscaled'"'"'s whois names the peer'"'"'s user, whose login is a verified email. A tagged machine signs no one in, a peer tailscaled does not know is refused, and with tailscaled unreachable every request is refused.'
section 'Tailscale proxy: headers from this machine only' tailscale proxy_mode_trusts_the_headers_only_from_this_machine \
  'The proxy'"'"'s headers name the user from a local peer, and are refused from any other.'

printf '\n## Every auth test (rung 2)\n\n' >>"$out"
status=0
tests=$(mise exec -- cargo test --locked -p cairn-auth 2>&1) || status=$?
[ "$status" -eq 0 ] || { mismatches=$((mismatches + 1)); echo "prove.sh: the auth tests failed" >&2; }
{
  printf '`cargo test -p cairn-auth` exit status %s:\n\n| Suite | Passed |\n|---|---|\n' "$status"
  awk '/^ *Running unittests/ { suite = $3 } /^ *Running tests\// { suite = $2 } /^ *Doc-tests/ { suite = "doc tests" }
       /^test result:/ { print "| `" suite "` | " $4 " |" }' <<<"$tests"
} >>"$out"

printf '\n## Planted bug: the audience check skipped\n\n' >>"$out"
tree=$work/tree
rsync -a --delete --exclude target --exclude node_modules --exclude .jj --exclude .git "$repo/" "$tree/"
oidc=$tree/crates/auth/src/oidc.rs
perl -0pi -e 's/\.id_token_verifier\(\)/.id_token_verifier()\n            .require_audience_match(false)/' "$oidc"
if cmp -s "$oidc" "$repo/crates/auth/src/oidc.rs"; then
  mismatches=$((mismatches + 1))
  echo "prove.sh: the planted bug was not planted" >&2
fi
case_name=oidc::a_spoiled_id_token_is_refused
status=0
planted_output=$(cd "$tree" && mise exec -- cargo test --quiet --locked -p cairn-auth --test oidc -- --exact "$case_name" 2>&1) || status=$?
[ "$status" -ne 0 ] || { mismatches=$((mismatches + 1)); echo "prove.sh: the planted bug went unnoticed" >&2; }
# cp, not rsync -a: a fresh mtime makes cargo rebuild the restored file.
cp "$repo/crates/auth/src/oidc.rs" "$oidc"
status_after=0
after_output=$(cd "$tree" && mise exec -- cargo test --quiet --locked -p cairn-auth --test oidc -- --exact "$case_name" 2>&1) || status_after=$?
[ "$status_after" -eq 0 ] || { mismatches=$((mismatches + 1)); echo "prove.sh: the restored provider fails" >&2; }
{
  printf 'In `crates/auth/src/oidc.rs`, the ID token verifier is told not to require the audience to match Cairn'"'"'s client id. `%s` exit status %s:\n\n```\n' "$case_name" "$status"
  grep -E 'panicked|Audience|^test result' <<<"$planted_output" | sed -E 's/ \([0-9]+\)//' | head -4
  printf '```\n\nRestored, exit status %s:\n\n```\n' "$status_after"
  grep -E '^test result' <<<"$after_output"
  printf '```\n'
} >>"$out"

mv "$out" "$readme"
if [ "$mismatches" -gt 0 ]; then
  echo "prove.sh: $mismatches outcome(s) differed from the expected" >&2
  exit 1
fi
echo "prove.sh: every outcome was the expected one; wrote $readme"
