#!/usr/bin/env bash
# Generates briefs/proof/2.4/README.md: the fixtures walked through derive's pass 5 and the
# derived guards by `cargo run -p cairn-engine --example blocking_walkthrough -- fixtures`
# (the vendor evaluation's frontier after each step, checked against the table
# fixtures/README.md states; the frontier before and after a completion; a blocked node and
# its origin blockers; a snooze holding then lifting; a stalled journey and what it waits on;
# a guard rejection and a bypass; the consequences of a patch; an auto-reach milestone on its
# date; the pass's cost at the limits), the brief's test suites, and the planted bug (snoozed
# nodes left on the acting frontier, caught by the D5 scenario, then passing again once
# restored). Exits non-zero if any outcome differs from the one expected.
#
# usage: briefs/proof/2.4/prove.sh WORK_DIR
#
# WORK_DIR holds a copy of the tree for the planted bug; the repository itself is never
# modified, apart from the README this writes.
# shellcheck disable=SC2016 # backticks in single quotes are Markdown code spans
set -euo pipefail
repo=$(cd "$(dirname "$0")/../../.." && pwd)
work=${1:?usage: prove.sh WORK_DIR}
mkdir -p "$work"
work=$(cd "$work" && pwd)
readme=$repo/briefs/proof/2.4/README.md
export CARGO_TERM_COLOR=never MISE_TRUSTED_CONFIG_PATHS=$work/tree
mismatches=0
out=$readme.tmp
miss() {
  mismatches=$((mismatches + 1))
  echo "prove.sh: $1" >&2
}

cd "$repo"
cat >"$out" <<'EOF'
# Proof for brief 2.4: auto-reach, blocking, the frontier, snooze, stalled, stale, and the derived guards

Generated by `briefs/proof/2.4/prove.sh WORK_DIR`; do not edit by hand. The script fails if
any outcome below differs from the one expected.

What this shows: a journey now says what can be acted on. `derive` decides, in one sweep over
the effective dependency graph, what satisfies dependencies (terminal work; a skip once its kept
work does; a group once its children and gates do; an `auto_reach` milestone on its date), and
from that each node's `deps_done`, whether it is blocked or actionable, the frontier, the
acting frontier (without snoozes that hold and `auto_reach` dates still ahead), and, when
nothing can be acted on, what the journey waits on. A blocked node lists what blocks it itself;
what it inherits is listed once, on the ancestor that holds it. The write path now checks
relevance and `deps_done` on every completing transition against one derive of the graph the
whole patch produces, records what a bypass accepted, keeps snoozes on nodes in scope and out
of wait cycles, and reports what a patch newly caused (D7). The sections below are printed by
`cargo run -p cairn-engine --example blocking_walkthrough -- fixtures`.

EOF

status=0
walkthrough=$(mise exec -- cargo run --quiet --locked -p cairn-engine --all-features --example blocking_walkthrough -- fixtures 2>&1 | grep -v '^mbx') || status=$?
[ "$status" -eq 0 ] || miss "the walkthrough failed: $walkthrough"
printf '%s\n' "$walkthrough" >>"$out"

# The frontier table is what fixtures/README.md states, row for row.
stated=0
while IFS= read -r line; do
  grep -qxF -- "$line" fixtures/README.md || miss "fixtures/README.md does not state: $line"
  stated=$((stated + 1))
done < <(awk '/^## The vendor evaluation.s frontier/ { p = 1 } /^## Before and after a completion/ { p = 0 } p && /^\| [0-9]/' <<<"$walkthrough")
[ "$stated" -eq 8 ] || miss "expected 8 frontier rows, printed $stated"
grep -q 'gating node `n_final_report`' <<<"$walkthrough" || miss "the stall does not name its gating node"
grep -q 'caused by mutations {1, 2}' <<<"$walkthrough" || miss "the rejection does not name both mutations"
grep -q '`n_findings` became stale' <<<"$walkthrough" || miss "the inserted dependency reported no stale completion"
printf '\nThe %s rows of the frontier table above are the ones `fixtures/README.md` states for the vendor evaluation; the J3 matrix entry "vendor evaluation: the frontier at each step" checks the same values.\n' "$stated" >>"$out"

printf '\n## The suites\n\n' >>"$out"
status=0
suites=$(mise exec -- cargo test --quiet --locked -p cairn-engine --all-features \
  --test blocking --test guards --test consequences --test matrix \
  --test property_blocking --test property_dependencies --test cost_blocking 2>&1) || status=$?
[ "$status" -eq 0 ] || miss "the suites failed"
{
  printf 'Pass 5 by example, the derived guards, D7, the J3 matrix with this brief'"'"'s entries, the property tests (among them the reference test of blocking over the entry chain against the plain expansion), and the cost test. In cargo'"'"'s order: `blocking.rs`, `consequences.rs`, `cost_blocking.rs`, `guards.rs`, `matrix.rs`, `property_blocking.rs`, `property_dependencies.rs`:\n\n```\n'
  grep -E '^test result' <<<"$suites" | sed -E 's/; finished in .*//'
  printf '```\n'
} >>"$out"

printf '\n## Planted bug: snoozed nodes left on the acting frontier\n\n' >>"$out"
tree=$work/tree
rsync -a --delete --exclude target --exclude node_modules --exclude .jj --exclude .git "$repo/" "$tree/"
blocking=$tree/crates/engine/src/derive/blocking.rs
perl -pi -e 's/if flags\.snoozed\.is_none\(\) && sweep\.reach_ahead\(key\)\.is_none\(\) \{/if sweep.reach_ahead(key).is_none() {/' "$blocking"
cmp -s "$blocking" "$repo/crates/engine/src/derive/blocking.rs" && miss "the acting frontier's snooze check was not found"
status=0
planted_output=$(cd "$tree" && mise exec -- cargo test --quiet --all-features -p cairn-engine --test blocking 2>&1) || status=$?
[ "$status" -ne 0 ] || miss "the planted bug went unnoticed"
grep -q "stalled_names_a_gate_a_snooze_and_an_auto_reach_date" <<<"$planted_output" \
  || miss "the D5 scenario did not fail"
# cp, not rsync -a: a fresh mtime makes cargo rebuild the restored file.
cp "$repo/crates/engine/src/derive/blocking.rs" "$blocking"
status_after=0
after_output=$(cd "$tree" && mise exec -- cargo test --quiet --all-features -p cairn-engine --test blocking 2>&1) || status_after=$?
[ "$status_after" -eq 0 ] || miss "the restored check fails"
{
  printf 'In `crates/engine/src/derive/blocking.rs` the acting frontier keeps snoozed nodes. `cargo test -p cairn-engine --test blocking` exit status %s:\n\n```\n' "$status"
  grep -E "^thread '|^test result" <<<"$planted_output" | sed -E "s/ \\([0-9]+\\)//; s/; finished in .*//" | head -6
  printf '```\n\nRestored, exit status %s:\n\n```\n' "$status_after"
  grep -E '^test result' <<<"$after_output" | sed -E 's/; finished in .*//'
  printf '```\n'
} >>"$out"

mv "$out" "$readme"
if [ "$mismatches" -gt 0 ]; then
  echo "prove.sh: $mismatches outcome(s) differed from the expected" >&2
  exit 1
fi
echo "prove.sh: every outcome was the expected one; wrote $readme"
