#!/usr/bin/env bash
# Generates briefs/proof/4.5/README.md: the browser host in Chromium against the server.
# Builds the module (mise run build:wasm), walks the fixtures through the server's service
# natively to record its answers and time the derive at the limits natively (the
# cairn-wasm-cases binary, optimized), then runs the browser tests (rung 6) keeping what each
# found: every call over every fixture's document compared with the server byte for byte, the
# in-browser root's transcript, the version-skew refusal, and the benchmark in the browser.
# Then the native suites' counts and the planted bug: the server's memo keyed without the
# deployment revision, caught by the agreement test after an entity merge. Exits non-zero if
# any outcome differs from the one expected.
#
# usage: briefs/proof/4.5/prove.sh WORK_DIR
#
# WORK_DIR holds what the browser tests found and a copy of the tree for the planted bug; the
# repository itself is never modified, apart from the README this writes and the build
# outputs under web/wasm/dist/.
# shellcheck disable=SC2016 # backticks in single quotes are Markdown code spans
set -euo pipefail
repo=$(cd "$(dirname "$0")/../../.." && pwd)
work=${1:?usage: prove.sh WORK_DIR}
mkdir -p "$work"
work=$(cd "$work" && pwd)
readme=$repo/briefs/proof/4.5/README.md
export CARGO_TERM_COLOR=never MISE_TRUSTED_CONFIG_PATHS=$work/tree
mismatches=0
miss() {
  mismatches=$((mismatches + 1))
  echo "prove.sh: $1" >&2
}

cd "$repo"
found=$work/found
cases=$repo/web/wasm/dist/cases
rm -rf "$found"
mise run build:wasm
mise exec -- cargo run --quiet --locked --release -p cairn-wasm --features server \
  --bin cairn-wasm-cases -- "$cases" --bench
(cd web/wasm && CAIRN_PROOF_OUT=$found "$repo/node_modules/.bin/playwright" test --reporter=line) \
  || miss "the browser tests failed"
section() {
  node web/wasm/e2e/proof.ts "$found" "$cases" "$1" || miss "the $1 section reports a difference"
}

native=$(mise exec -- cargo test --locked -p cairn-wasm --all-features 2>&1) || miss "the native suites failed"
counts=$(awk '/Running (unittests|tests\/)/ { name = ($2 == "unittests") ? $3 : $2 } /^test result:/ { if (name != "" && $4 > 0) print "| `" name "` | " $4 " passed, " $6 " failed |"; name = "" }' <<<"$native")

# The planted bug, in a copy: the server's memo matches a derivation without its deployment
# revision, so after an entity merge it answers the derive from before the merge.
tree=$work/tree
rsync -a --delete --exclude target --exclude node_modules --exclude dist --exclude .jj --exclude .git "$repo/" "$tree/"
memo=$tree/crates/service/src/derived.rs
sed -i 's/position(|entry| entry.key == \*key)/position(|entry| entry.key.journey == key.journey \&\& entry.key.revision == key.revision \&\& entry.key.today == key.today \&\& entry.key.viewer == key.viewer)/' "$memo"
cmp -s "$memo" "$repo/crates/service/src/derived.rs" && miss "the planted bug was not planted"
agreement=(cargo test --locked -p cairn-wasm --all-features --test agreement every_call_over_every_fixture)
status=0
planted=$(cd "$tree" && mise exec -- "${agreement[@]}" 2>&1) || status=$?
[ "$status" -ne 0 ] || miss "the planted bug went unnoticed"
cp "$repo/crates/service/src/derived.rs" "$memo"
status_after=0
(cd "$tree" && mise exec -- "${agreement[@]}" >/dev/null 2>&1) || status_after=$?
[ "$status_after" -eq 0 ] || miss "the restored tree fails the agreement test"
caught=$(grep -E '^vendor-evaluation after an entity merge: ' <<<"$planted" || true)
[ -n "$caught" ] || miss "the planted bug was not caught after the entity merge"

out=$readme.tmp
{
  cat <<'EOF'
# Proof for brief 4.5: Wasm host

Generated by `briefs/proof/4.5/prove.sh WORK_DIR`; do not edit by hand. The script fails if
any outcome below differs from the one expected.

The engine and the service now run in the browser. A domain document from the server is
derived in a web worker by the engine compiled to wasm, and every projection, a proposal
preview, a local apply, and route files answer there exactly what the server answers. The
in-browser root runs the whole service over the memory store, seeded with the fixtures, with
no server. A document from another engine version is refused before it is read.

## Every call agrees with the server, byte for byte

The server's side is the service as the server binary assembles it, over the memory store,
seeded with every fixture and read as the in-browser root's local user (verified for each
fixture's lead, so the lead is the viewer) at 2026-10-12T12:00Z
(`crates/wasm/src/cases`). Each document's calls ran in Chromium: the derive, projections,
previews, and local applies in the derive worker, which holds the server's document; route
files and touched sets in the page's own instance. Each answer was compared with the
server's as text. Per fixture: the derive, every canvas level (the top and each container),
every node's trace and both explanation lists, the decision view, timeline, status summary,
next list, list, mine, and snapshot, two proposals previewed (a note; a note and a start),
the walk's patch applied locally against the server's commit, and its touched set. Then each
journey after that patch, the route files (each fixture's version 1 exported, imported back,
and its draft exported), the vendor evaluation after a stakeholder was merged into a new
entity (a deployment change that moves no journey and not the viewer), and the document at the limits
(`node_count_max` nodes, containment at the depth limit), whose answers are the native
build's: there the point is the wasm build on its small stack.

EOF
  section agreement
  cat <<'EOF'

## The in-browser root

Seeded on load with every fixture, each journey's document came from the root and was
derived in the worker:

EOF
  section root
  cat <<'EOF'

## Version skew

The vendor evaluation's document with its engine version set to `9.0.0`. Before it, the
worker projects the journey it holds and the page computes touched sets. Once the worker is
posted it, it refuses that load, then the journey it held, then even this engine's own
document; once the page's engine sees it (`accepts` answers false), touched sets (the safe
retry), local applies, previews, and the root's writes are refused too, until a reload.

EOF
  section skew
  cat <<'EOF'

## The derive benchmark at the limits

On the document at the limits (the date network's cost-test graph as a journey); reported,
not gated (ARCHITECTURE, Date network). The browser times each call from the page, so its
figures include posting the document to the worker and the answer back.

EOF
  section bench
  cat <<'EOF'

## The native suites

`cargo test -p cairn-wasm --all-features`: the same calls through this crate natively against
the service (`tests/agreement.rs`), a document derived and projected and another engine's
refused (`tests/document.rs`), and the root's apply, stale refusals, notifications, and
API-shaped answers (`tests/root.rs`).

| Suite | Result |
|---|---|
EOF
  printf '%s\n' "$counts"
  cat <<'EOF'

## The planted bug

The service's memo matching a derivation without its deployment revision answers the
vendor evaluation's derive from before the entity merge; the agreement test fails on every
call over the merged document:

```text
EOF
  printf '%s\n' "$caught"
  echo '```'
} >"$out"

mv "$out" "$readme"
if [ "$mismatches" -ne 0 ]; then
  echo "prove.sh: $mismatches outcomes differ from those expected" >&2
  exit 1
fi
echo "prove.sh: wrote $readme"
