#!/usr/bin/env bash
# Generates briefs/proof/3.1/README.md: a journey holding every record committed to a Turso
# file and loaded back equal, a revision conflict, a failure between state rows and events
# leaving nothing, an entity create riding in a journey patch, a create at a deleted
# journey's id, an oversize commit, the glossary found as tables and columns (all from the
# `store_proof` example in crates/store-turso), the conformance suite's count per backend
# (rung 4), and the planted bug (events appended before the revision check, caught by the
# conformance suite). Exits non-zero if any outcome differs from the one expected.
#
# usage: briefs/proof/3.1/prove.sh WORK_DIR
#
# WORK_DIR holds the proof's database files and a copy of the tree for the planted bug; the
# repository itself is never modified, apart from the README this writes.
# shellcheck disable=SC2016 # backticks in single quotes are Markdown code spans
set -euo pipefail
repo=$(cd "$(dirname "$0")/../../.." && pwd)
work=${1:?usage: prove.sh WORK_DIR}
mkdir -p "$work"
work=$(cd "$work" && pwd)
readme=$repo/briefs/proof/3.1/README.md
export CARGO_TERM_COLOR=never MISE_TRUSTED_CONFIG_PATHS=$work/tree
mismatches=0
out=$readme.tmp

cd "$repo"
cat >"$out" <<'EOF'
# Proof for brief 3.1: the store

Generated by `briefs/proof/3.1/prove.sh WORK_DIR`; do not edit by hand. The script fails if
any outcome below differs from the one expected.

What this shows: the store persists what an accepted patch produced, whole or not at all,
and answers from it. Each section below runs against a Turso database file through the
`Store` trait (`cargo run -p cairn-store-turso --example store_proof`); the change sets are
built by hand, as an engine would produce them, since the store has no engine dependency.
The conformance suite then runs the same cases against both backends, each counted on its
own, and a planted bug in the memory backend is caught by it.
EOF

status=0
mise exec -- cargo run --quiet --locked -p cairn-store-turso --example store_proof -- "$work/proof" >>"$out" || status=$?
if [ "$status" -ne 0 ]; then
  mismatches=$((mismatches + 1))
  echo "prove.sh: the store proof reported unexpected outcomes" >&2
fi

printf '\n## The conformance suite, per backend (rung 4)\n\n' >>"$out"
status=0
ladder=$(mise run check:4 2>&1) || status=$?
[ "$status" -eq 0 ] || { mismatches=$((mismatches + 1)); echo "prove.sh: rung 4 failed" >&2; }
{
  printf '`mise run check:4` exit status %s. Each backend is its own suite, so neither can vanish behind the other:\n\n' "$status"
  printf '| Suite | Tests |\n|---|---|\n'
  grep -E 'ladder: rung 4: suite' <<<"$ladder" | sed -E 's/.*suite store conformance: ([a-z]+): ([0-9]+) tests/| \1 | \2 |/'
  printf '\nThe Turso suite adds its own cases: two creates of one journey in flight, two creates of one entity key riding in two journeys at once, a hard delete racing a node insert into the journey, a long commit beside a read of its journey and a commit to another, a crash in the middle of a commit, a new entity reference racing a merge of the entity, a proposal racing its journey'"'"'s deletion, history paged while an earlier-numbered commit is in flight, and the foreign-key gap (DECISIONS.md).\n'
} >>"$out"

printf '\n## Planted bug: events appended outside the all-or-nothing step\n\n' >>"$out"
tree=$work/tree
rsync -a --delete --exclude target --exclude node_modules --exclude .jj --exclude .git "$repo/" "$tree/"
memory=$tree/crates/store/src/memory/mod.rs
perl -0pi -e 's/(\n(\s*)state\.check_revisions\(commit, &shape\)\?;)/\n$2for event in &commit.change_set.events {\n$2    let seq = state.next_seq;\n$2    state.next_seq += 1;\n$2    state.events.push(LoggedEvent { seq, event: event.clone() });\n$2}$1/' "$memory"
if cmp -s "$memory" "$repo/crates/store/src/memory/mod.rs"; then
  mismatches=$((mismatches + 1))
  echo "prove.sh: the planted bug was not planted" >&2
fi
case_name=conformance::a_revision_conflict_is_rejected_and_leaves_state_untouched
status=0
planted_output=$(cd "$tree" && mise exec -- cargo test --quiet --locked -p cairn-store --all-features --test conformance -- "$case_name" 2>&1) || status=$?
[ "$status" -ne 0 ] || { mismatches=$((mismatches + 1)); echo "prove.sh: the planted bug went unnoticed" >&2; }
# cp, not rsync -a: a fresh mtime makes cargo rebuild the restored file.
cp "$repo/crates/store/src/memory/mod.rs" "$memory"
status_after=0
after_output=$(cd "$tree" && mise exec -- cargo test --quiet --locked -p cairn-store --all-features --test conformance -- "$case_name" 2>&1) || status_after=$?
[ "$status_after" -eq 0 ] || { mismatches=$((mismatches + 1)); echo "prove.sh: the restored backend fails" >&2; }
{
  printf 'In `crates/store/src/memory/mod.rs`, the commit appends its events to the log before it checks revisions, so a stale commit leaves its events behind. `%s` exit status %s:\n\n```\n' "$case_name" "$status"
  grep -E 'panicked|^test result' <<<"$planted_output" | sed -E 's/ \([0-9]+\)//' | head -3
  printf '```\n\nRestored, exit status %s:\n\n```\n' "$status_after"
  grep -E '^test result' <<<"$after_output"
  printf '```\n'
} >>"$out"

mv "$out" "$readme"
if [ "$mismatches" -gt 0 ]; then
  echo "prove.sh: $mismatches outcome(s) differed from the expected" >&2
  exit 1
fi
echo "prove.sh: every outcome was the expected one; wrote $readme"
