#!/usr/bin/env bash
# Generates briefs/proof/1.1/README.md: `mise run check` on a clean copy of the tree, then on
# copies with one planted violation each, showing the lines of output that matter. Exits
# non-zero if any scenario's outcome differs from the one it expects.
#
# usage: briefs/proof/1.1/prove.sh WORK_DIR
#
# WORK_DIR holds the copy of the tree the scenarios run in; the repository itself is never
# modified, apart from the README this writes.
# shellcheck disable=SC2016 # backticks in single quotes are Markdown code spans
set -euo pipefail
repo=$(cd "$(dirname "$0")/../../.." && pwd)
work=${1:?usage: prove.sh WORK_DIR}
work=$(realpath -m "$work")
case "$work/" in
  "$repo/"*) echo "prove.sh: WORK_DIR must be outside the repository ($repo)" >&2; exit 2 ;;
esac
mkdir -p "$work"
tree=$work/tree
readme=$repo/briefs/proof/1.1/README.md
export CARGO_TERM_COLOR=never MISE_TRUSTED_CONFIG_PATHS=$tree
mismatches=0

reset_tree() {
  rsync -a --delete --exclude target --exclude node_modules --exclude .jj --exclude .git \
    "$repo/" "$tree/"
}

# A function whose body is LINES lines long, as clippy::too_many_lines counts them.
long_function() {
  local lines=$1
  printf '\n/// Adds up a run of constants.\n#[must_use]\npub fn long_function() -> u32 {\n'
  printf '    let mut total = 0;\n'
  for step in $(seq 1 $((lines - 2))); do printf '    total += %d;\n' "$step"; done
  printf '    total\n}\n'
}

# scenario TITLE EXPECTED_EXIT(0|nonzero) PLANT_DESCRIPTION [ENV=VALUE...]
# The tree has been reset and planted by the caller; this runs check and writes the section.
scenario() {
  local title=$1 expected=$2 plant=$3
  shift 3
  local log status=0 outcome
  log=$(cd "$tree" && env "$@" mise run check 2>&1) || status=$?
  if [ "$status" -eq 0 ]; then outcome=0; else outcome=nonzero; fi
  if [ "$outcome" != "$expected" ]; then
    mismatches=$((mismatches + 1))
    echo "prove.sh: MISMATCH in '$title': expected exit $expected, got $status" >&2
    printf '%s\n' "$log" >&2
  fi
  {
    printf '\n## %s\n\n%s\n\n`mise run check` exit status: %s (expected %s).\n\n```\n' \
      "$title" "$plant" "$status" "$expected"
    # The lines that matter: which rungs exist, compiler errors and their locations,
    # rustfmt's diff header, and the ladder's summary. Paths are relative to the tree.
    awk '/^ladder: summary$/ { summary = 1 }
         summary || /^ladder: rungs that exist/ || /^(error(\[|:)|Diff in | +--> )/' <<<"$log" \
      | sed "s|$tree/||g"
    printf '```\n'
  } >>"$readme.tmp"
}

cat >"$readme.tmp" <<'EOF'
# Proof for brief 1.1: workspace, lints, tasks, CI

Generated by `briefs/proof/1.1/prove.sh WORK_DIR`; do not edit by hand. Each section copies
the tree into `WORK_DIR`, plants one change, runs `mise run check`, and shows the exit status
and the lines of output that matter. The script fails if any outcome differs from the one
expected.

What this shows: a fresh tree passes `mise run check`, which runs exactly the rungs that exist
(rung 1); rung 1 fails on a stray `unwrap`, on a 71-line function (and accepts 70), on a
formatting error, on HashMap in the engine crate once it exists, on a crate that drops the
workspace lints, and on a missing tool; and a rung that ran zero tests fails the ladder.
EOF

reset_tree
scenario "Clean tree" 0 "No change."

reset_tree
cat >>"$tree/crates/schema/src/lib.rs" <<'EOF'

/// Reads a count.
///
/// # Panics
///
/// When the text is not a count.
#[must_use]
pub fn count_from_text(text: &str) -> u32 {
    text.parse().unwrap()
}
EOF
scenario "Stray unwrap" nonzero 'Planted: a public function in the schema crate ending in `text.parse().unwrap()`.'

reset_tree
long_function 70 >>"$tree/crates/schema/src/lib.rs"
scenario "70-line function" 0 "Planted: a function whose body is 70 lines, the limit (PRACTICES, Code shape)."

reset_tree
long_function 71 >>"$tree/crates/schema/src/lib.rs"
scenario "71-line function" nonzero "Planted: the same function with a 71-line body."

reset_tree
printf '\n/// Badly spaced.\npub const   SPACED : u32=1;\n' >>"$tree/crates/schema/src/lib.rs"
scenario "Formatting error" nonzero 'Planted: `pub const   SPACED : u32=1;`.'

reset_tree
cat >"$tree/mise-tasks/check/4" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/../.."
LADDER_RUNG=4
source scripts/ladder-lib.sh
output=$(cargo test --locked --workspace -- store_conformance:: 2>&1)
ladder_suite "store conformance" "$(awk '/^running [0-9]+ tests?$/ { total += $2 } END { print total + 0 }' <<<"$output")" tests
ladder_rung_end
EOF
chmod +x "$tree/mise-tasks/check/4"
scenario "A rung that ran zero tests" nonzero "Planted: a rung 4 (\`mise-tasks/check/4\`) that runs the workspace tests named \`store_conformance::\` and reports how many ran. No crate has such tests yet, so it reports zero."

reset_tree
mkdir -p "$tree/crates/engine/src"
cat >"$tree/crates/engine/Cargo.toml" <<'EOF'
[package]
name = "cairn-engine"
description = "Planted engine crate."
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true
EOF
cat >"$tree/crates/engine/src/lib.rs" <<'EOF'
//! Planted engine crate.

/// Counts each value.
#[must_use]
pub fn count_each(values: &[u32]) -> std::collections::HashMap<u32, u32> {
    let mut counts = std::collections::HashMap::new();
    for value in values {
        *counts.entry(*value).or_insert(0) += 1;
    }
    counts
}
EOF
(cd "$tree" && mise exec -- cargo generate-lockfile --offline >/dev/null 2>&1)
scenario "HashMap in the engine crate" nonzero 'Planted: a `crates/engine` crate (`cairn-engine`) whose public function returns a `std::collections::HashMap`.'

reset_tree
sed -i '/^\[lints\]$/,$d' "$tree/crates/schema/Cargo.toml"
scenario "A crate that drops the workspace lints" nonzero 'Planted: the schema crate without `[lints] workspace = true`.'

reset_tree
# mise stops providing node, and a node that fails comes first on PATH, so no other node
# on this machine stands in for it.
mkdir -p "$work/no-node"
printf '#!/bin/sh\necho "node: not installed" >&2\nexit 127\n' >"$work/no-node/node"
chmod +x "$work/no-node/node"
scenario "A missing tool" nonzero 'Planted: no file change; mise stops providing `node` (`MISE_DISABLE_TOOLS=node`) and a `node` that fails comes first on `PATH`, as on a machine where it was never installed.' \
  MISE_DISABLE_TOOLS=node "PATH=$work/no-node:$PATH"

mv "$readme.tmp" "$readme"
if [ "$mismatches" -gt 0 ]; then
  echo "prove.sh: $mismatches scenario(s) did not behave as expected" >&2
  exit 1
fi
echo "prove.sh: every scenario behaved as expected; wrote $readme"
