//! The in-browser root's proposals (I6, C14; brief 5.7): created against a domain with a
//! client-generated id, fetched, edited, previewed, applied, discarded, and refreshed by id
//! alone, and the upgrade, save-as-route, and re-link drafts (B7, B8, B9), each through the
//! same service calls as the server's `/api/{domain}/proposals`, `/api/proposals/{id}...`, and
//! `/api/journeys/{id}/{upgrade,save-as-route,relink}`, answering the API's JSON for them, so the
//! app's one data layer reviews a proposal on either host.

use std::collections::BTreeMap;

use cairn_engine::DraftError;
use cairn_schema::{
    Consequences, Domain, JourneyId, Lineage, Markdown, PatchId, PatchReceipt, Proposal,
    ProposalDraft, ProposalId, ProposalPreview, Revision, RevisionConflict, RouteId, Title,
    TouchedSet, VersionNumber,
};
use cairn_service::{ProposalWritten, ProposeError, ReadError, WriteError};
use serde::{Deserialize, Serialize};
use wasm_bindgen::prelude::wasm_bindgen;

use crate::error::{HostError, json, read};
use crate::now_or_never;
use crate::root::{BrowserRoot, PatchAnswer, failed};

/// `POST /api/{domain}/proposals`'s body, as the API's `ProposalCreate`.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ProposalCreate {
    /// The write's patch id (H5).
    pub patch_id: PatchId,
    /// The proposal's id, generated by the client (I6).
    pub id: ProposalId,
    /// Its content.
    pub draft: ProposalDraft,
}

/// `PATCH /api/proposals/{id}`'s body, as the API's `ProposalEdit`.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ProposalEdit {
    /// The write's patch id (H5).
    pub patch_id: PatchId,
    /// The proposal's editing revision the editor saw.
    pub base_revision: Revision,
    /// Its content.
    pub draft: ProposalDraft,
}

/// The body of `POST /api/proposals/{id}/discard` and `.../refresh`, as the API's `ProposalStep`.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ProposalStep {
    /// The write's patch id (H5).
    pub patch_id: PatchId,
    /// The proposal's editing revision the caller saw.
    pub base_revision: Revision,
}

/// `POST /api/proposals/{id}/apply`'s body, as the API's `ProposalApply`.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ProposalApply {
    /// The apply's patch id (H5).
    pub patch_id: PatchId,
    /// The proposal's editing revision the reviewer previewed.
    pub reviewed_revision: Revision,
    /// A note for each of the apply's events (J1).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub note: Option<Markdown>,
}

/// `POST /api/journeys/{id}/upgrade`'s body (B7), as the API's `UpgradeRequest`.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct UpgradeRequest {
    /// The proposal write's patch id (H5).
    pub patch_id: PatchId,
    /// The proposal's id, generated by the client (I6).
    pub proposal: ProposalId,
    /// The version to upgrade to.
    pub to: VersionNumber,
}

/// `POST /api/journeys/{id}/save-as-route`'s body (B8), as the API's `SaveAsRouteRequest`.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SaveAsRouteRequest {
    /// The proposal write's patch id (H5).
    pub patch_id: PatchId,
    /// The proposal's id, generated by the client (I6).
    pub proposal: ProposalId,
    /// The route the draft is of.
    pub route: RouteId,
    /// The route's name, when it is created.
    pub name: Title,
}

/// `POST /api/journeys/{id}/relink`'s body (B9), as the API's `RelinkRequest`.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RelinkRequest {
    /// The proposal write's patch id (H5).
    pub patch_id: PatchId,
    /// The proposal's id, generated by the client (I6).
    pub proposal: ProposalId,
    /// The route version to follow once it is applied.
    pub lineage: Lineage,
}

/// What a write to a proposal answers (I6), as the API's `ProposalAnswer`.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "outcome", rename_all = "snake_case", deny_unknown_fields)]
pub enum ProposalAnswer {
    /// Committed now: the receipt and the proposal as it now stands.
    Saved {
        /// The receipt.
        receipt: PatchReceipt,
        /// The proposal.
        proposal: Proposal,
    },
    /// The patch id was committed before with the same content (H5).
    AlreadySaved {
        /// The original receipt.
        receipt: PatchReceipt,
    },
    /// I6: a create naming a proposal id its caller already holds for this destination.
    Existing {
        /// The proposal.
        proposal: Proposal,
    },
}

impl From<ProposalWritten> for ProposalAnswer {
    fn from(written: ProposalWritten) -> Self {
        match written {
            ProposalWritten::Saved { receipt, proposal } => {
                ProposalAnswer::Saved { receipt, proposal }
            }
            ProposalWritten::AlreadySaved { receipt } => ProposalAnswer::AlreadySaved { receipt },
            ProposalWritten::Existing { proposal } => ProposalAnswer::Existing { proposal },
        }
    }
}

/// I6: a proposal's destination moved past the revision it was drafted against, as the API's
/// `StaleBase`.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct StaleBase {
    /// The destination's revision the proposal names, and its current one.
    pub conflict: RevisionConflict,
    /// What the intervening events touched (H5).
    pub intervening: TouchedSet,
}

/// `POST /api/proposals/{id}/preview`'s answer (C14, D7, I6), as the API's `ProposalReview`.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ProposalReview {
    /// The proposal, at the editing revision a reviewer applies.
    pub proposal: Proposal,
    /// Its unresolved items, the violations of its candidate, and for a journey the graph
    /// and frontier after.
    pub preview: ProposalPreview,
    /// D7, by journey: what applying it would newly cause.
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub consequences: BTreeMap<JourneyId, Consequences>,
    /// I6: present when the destination moved since drafting.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub stale: Option<StaleBase>,
}

/// A proposal write's failure, as the root reports it: the rejection, or what is missing.
fn write_failed(error: WriteError) -> HostError {
    match error {
        WriteError::Rejected(rejection) => HostError::Rejected { rejection },
        WriteError::Failed(error) => failed(error),
    }
}

/// A draft's failure: what is missing, the write's failure, or why it cannot be drafted (no
/// lineage, a version that is not newer, a draft too large), which the API answers as a
/// problem and the root as a failure with the same words.
fn propose_failed(error: ProposeError) -> HostError {
    match error {
        ProposeError::Draft(
            error @ (DraftError::JourneyMissing(_) | DraftError::VersionMissing(_)),
        ) => HostError::Missing {
            message: error.to_string(),
        },
        ProposeError::ProposalMissing(id) => HostError::Missing {
            message: format!("no proposal {id}"),
        },
        ProposeError::Draft(error) => failed(error),
        ProposeError::Write(error) => write_failed(error),
    }
}

fn proposal_id(id: &str) -> Result<ProposalId, HostError> {
    id.parse()
        .map_err(|error| HostError::unreadable("proposal", format!("{error:?}")))
}

fn journey_id(id: &str) -> Result<JourneyId, HostError> {
    id.parse()
        .map_err(|error| HostError::unreadable("journey", format!("{error:?}")))
}

impl BrowserRoot {
    /// I6: the proposal with this id, as `GET /api/proposals/{id}` answers it.
    ///
    /// # Errors
    ///
    /// [`HostError::Missing`] when there is none; when the store fails.
    pub fn proposal_of(&self, id: &ProposalId) -> Result<Proposal, HostError> {
        now_or_never(self.service().proposal(id))
            .map_err(failed)?
            .ok_or_else(|| HostError::Missing {
                message: format!("no proposal {id}"),
            })
    }

    /// I6: creates a proposal for `destination` as the local user at `now`, as
    /// `POST /api/{domain}/proposals` answers it.
    ///
    /// # Errors
    ///
    /// [`HostError::Rejected`] when the id is taken otherwise or the patch id is reused; when
    /// the store fails.
    pub fn create_proposal(
        &self,
        destination: &Domain,
        request: &ProposalCreate,
        now: &str,
    ) -> Result<ProposalAnswer, HostError> {
        let call = self.call(now)?;
        now_or_never(self.service().create_proposal(
            &call,
            request.patch_id.clone(),
            destination,
            &request.id,
            request.draft.clone(),
        ))
        .map(ProposalAnswer::from)
        .map_err(write_failed)
    }

    /// I6, H5: replaces the proposal's content against the editing revision its editor saw,
    /// as `PATCH /api/proposals/{id}` answers it.
    ///
    /// # Errors
    ///
    /// [`HostError::Missing`] when there is no such proposal; [`HostError::Rejected`] when it
    /// moved, is not open, or the patch id is reused; when the store fails.
    pub fn edit_proposal(
        &self,
        id: &ProposalId,
        request: &ProposalEdit,
        now: &str,
    ) -> Result<ProposalAnswer, HostError> {
        let call = self.call(now)?;
        let destination = self.proposal_of(id)?.destination;
        now_or_never(self.service().edit_proposal(
            &call,
            request.patch_id.clone(),
            &destination,
            id,
            request.base_revision,
            request.draft.clone(),
        ))
        .map(ProposalAnswer::from)
        .map_err(write_failed)
    }

    /// I6: discards the proposal, as `POST /api/proposals/{id}/discard` answers it.
    ///
    /// # Errors
    ///
    /// As [`BrowserRoot::edit_proposal`].
    pub fn discard_proposal(
        &self,
        id: &ProposalId,
        request: &ProposalStep,
        now: &str,
    ) -> Result<ProposalAnswer, HostError> {
        let call = self.call(now)?;
        let destination = self.proposal_of(id)?.destination;
        now_or_never(self.service().discard_proposal(
            &call,
            request.patch_id.clone(),
            &destination,
            id,
            request.base_revision,
        ))
        .map(ProposalAnswer::from)
        .map_err(write_failed)
    }

    /// I6: drafts the proposal again on its destination as it stands, the reviewer's choices
    /// carried over, as `POST /api/proposals/{id}/refresh` answers it. Its revision moves, so it
    /// must be reviewed again.
    ///
    /// # Errors
    ///
    /// As [`BrowserRoot::edit_proposal`], and when it cannot be drafted again.
    pub fn refresh_proposal(
        &self,
        id: &ProposalId,
        request: &ProposalStep,
        now: &str,
    ) -> Result<ProposalAnswer, HostError> {
        let call = self.call(now)?;
        now_or_never(self.service().refresh_proposal(
            &call,
            request.patch_id.clone(),
            id,
            request.base_revision,
        ))
        .map(ProposalAnswer::from)
        .map_err(propose_failed)
    }

    /// C14, D7, I6: what applying the proposal now would do, and what moved since it was
    /// drafted, as `POST /api/proposals/{id}/preview` answers it.
    ///
    /// # Errors
    ///
    /// [`HostError::Missing`] when there is no such proposal; when the store fails.
    pub fn preview_proposal(
        &self,
        id: &ProposalId,
        now: &str,
    ) -> Result<ProposalReview, HostError> {
        let call = self.call(now)?;
        let review =
            now_or_never(self.service().preview_proposal(&call, id)).map_err(
                |error| match error {
                    ReadError::ProposalMissing(id) => HostError::Missing {
                        message: format!("no proposal {id}"),
                    },
                    error => failed(error),
                },
            )?;
        Ok(ProposalReview {
            proposal: review.proposal,
            preview: review.preview,
            consequences: review.consequences,
            stale: review.stale.map(|stale| StaleBase {
                conflict: stale.conflict,
                intervening: stale.intervening,
            }),
        })
    }

    /// I6, H2: applies the proposal as the local user, its confirming user, at the editing
    /// revision they reviewed, as `POST /api/proposals/{id}/apply` answers it.
    ///
    /// # Errors
    ///
    /// [`HostError::Missing`] when there is no such proposal; [`HostError::Rejected`] as
    /// stale, invalid, or for a reused patch id; when the store fails.
    pub fn apply_proposal(
        &self,
        id: &ProposalId,
        request: &ProposalApply,
        now: &str,
    ) -> Result<PatchAnswer, HostError> {
        let call = self.call(now)?;
        let destination = self.proposal_of(id)?.destination;
        match now_or_never(self.service().apply_proposal(
            &call,
            request.patch_id.clone(),
            &destination,
            id,
            request.reviewed_revision,
            request.note.clone(),
        )) {
            Ok(written) => Ok(written.into()),
            Err(error) => Err(write_failed(error)),
        }
    }

    /// B7: proposes upgrading `journey` to a newer version of its route, as
    /// `POST /api/journeys/{id}/upgrade` answers it.
    ///
    /// # Errors
    ///
    /// [`HostError::Missing`] for a journey or version that does not exist; a failure when the
    /// journey follows no route or the version is not newer; as a proposal write.
    pub fn upgrade(
        &self,
        journey: &JourneyId,
        request: &UpgradeRequest,
        now: &str,
    ) -> Result<ProposalAnswer, HostError> {
        let call = self.call(now)?;
        now_or_never(self.service().propose_upgrade(
            &call,
            request.patch_id.clone(),
            &request.proposal,
            journey,
            request.to,
        ))
        .map(ProposalAnswer::from)
        .map_err(propose_failed)
    }

    /// B8: proposes saving `journey`'s structure as a draft of a route, as
    /// `POST /api/journeys/{id}/save-as-route` answers it.
    ///
    /// # Errors
    ///
    /// As [`BrowserRoot::upgrade`].
    pub fn save_as_route(
        &self,
        journey: &JourneyId,
        request: &SaveAsRouteRequest,
        now: &str,
    ) -> Result<ProposalAnswer, HostError> {
        let call = self.call(now)?;
        now_or_never(self.service().propose_save_as_route(
            &call,
            request.patch_id.clone(),
            &request.proposal,
            journey,
            &request.route,
            &request.name,
        ))
        .map(ProposalAnswer::from)
        .map_err(propose_failed)
    }

    /// B9: proposes re-linking `journey` to a published version, as
    /// `POST /api/journeys/{id}/relink` answers it.
    ///
    /// # Errors
    ///
    /// As [`BrowserRoot::upgrade`].
    pub fn relink(
        &self,
        journey: &JourneyId,
        request: &RelinkRequest,
        now: &str,
    ) -> Result<ProposalAnswer, HostError> {
        let call = self.call(now)?;
        now_or_never(self.service().propose_relink(
            &call,
            request.patch_id.clone(),
            &request.proposal,
            journey,
            &request.lineage,
        ))
        .map(ProposalAnswer::from)
        .map_err(propose_failed)
    }
}

#[wasm_bindgen]
impl BrowserRoot {
    /// I6: proposal `id`, as `GET /api/proposals/{id}` answers it.
    ///
    /// # Errors
    ///
    /// The JSON of a [`HostError`]: no such proposal, or an unreadable input.
    pub fn proposal(&self, id: &str) -> Result<String, String> {
        Ok(json(&self.proposal_of(&proposal_id(id)?)?))
    }

    /// I6: creates a proposal for `destination` (the JSON of a `Domain`) at `now`: `request`
    /// is the JSON of a [`ProposalCreate`]; the answer is the JSON of a [`ProposalAnswer`].
    ///
    /// # Errors
    ///
    /// The JSON of a [`HostError`], the rejection among them.
    pub fn propose(&self, destination: &str, request: &str, now: &str) -> Result<String, String> {
        let destination: Domain = read("destination", destination)?;
        let request: ProposalCreate = read("proposal create", request)?;
        Ok(json(&self.create_proposal(&destination, &request, now)?))
    }

    /// I6: edits proposal `id`: `request` is the JSON of a [`ProposalEdit`].
    ///
    /// # Errors
    ///
    /// The JSON of a [`HostError`], the rejection among them.
    #[wasm_bindgen(js_name = editProposal)]
    pub fn edit_proposal_json(&self, id: &str, request: &str, now: &str) -> Result<String, String> {
        let request: ProposalEdit = read("proposal edit", request)?;
        Ok(json(&self.edit_proposal(
            &proposal_id(id)?,
            &request,
            now,
        )?))
    }

    /// I6: discards proposal `id`: `request` is the JSON of a [`ProposalStep`].
    ///
    /// # Errors
    ///
    /// The JSON of a [`HostError`], the rejection among them.
    #[wasm_bindgen(js_name = discardProposal)]
    pub fn discard_proposal_json(
        &self,
        id: &str,
        request: &str,
        now: &str,
    ) -> Result<String, String> {
        let request: ProposalStep = read("proposal step", request)?;
        Ok(json(&self.discard_proposal(
            &proposal_id(id)?,
            &request,
            now,
        )?))
    }

    /// I6: refreshes proposal `id` on its destination as it stands: `request` is the JSON of
    /// a [`ProposalStep`].
    ///
    /// # Errors
    ///
    /// The JSON of a [`HostError`], the rejection among them.
    #[wasm_bindgen(js_name = refreshProposal)]
    pub fn refresh_proposal_json(
        &self,
        id: &str,
        request: &str,
        now: &str,
    ) -> Result<String, String> {
        let request: ProposalStep = read("proposal step", request)?;
        Ok(json(&self.refresh_proposal(
            &proposal_id(id)?,
            &request,
            now,
        )?))
    }

    /// C14, I6: previews proposal `id` at `now`; the answer is the JSON of a
    /// [`ProposalReview`].
    ///
    /// # Errors
    ///
    /// The JSON of a [`HostError`].
    #[wasm_bindgen(js_name = previewProposal)]
    pub fn preview_proposal_json(&self, id: &str, now: &str) -> Result<String, String> {
        Ok(json(&self.preview_proposal(&proposal_id(id)?, now)?))
    }

    /// I6: applies proposal `id`: `request` is the JSON of a [`ProposalApply`]; the answer
    /// is the JSON of a [`PatchAnswer`].
    ///
    /// # Errors
    ///
    /// The JSON of a [`HostError`], the rejection among them.
    #[wasm_bindgen(js_name = applyProposal)]
    pub fn apply_proposal_json(
        &self,
        id: &str,
        request: &str,
        now: &str,
    ) -> Result<String, String> {
        let request: ProposalApply = read("proposal apply", request)?;
        Ok(json(&self.apply_proposal(
            &proposal_id(id)?,
            &request,
            now,
        )?))
    }

    /// B7: proposes upgrading `journey`: `request` is the JSON of an [`UpgradeRequest`].
    ///
    /// # Errors
    ///
    /// The JSON of a [`HostError`].
    #[wasm_bindgen(js_name = proposeUpgrade)]
    pub fn upgrade_json(&self, journey: &str, request: &str, now: &str) -> Result<String, String> {
        let request: UpgradeRequest = read("upgrade request", request)?;
        Ok(json(&self.upgrade(&journey_id(journey)?, &request, now)?))
    }

    /// B8: proposes saving `journey` as a route: `request` is the JSON of a
    /// [`SaveAsRouteRequest`].
    ///
    /// # Errors
    ///
    /// The JSON of a [`HostError`].
    #[wasm_bindgen(js_name = proposeSaveAsRoute)]
    pub fn save_as_route_json(
        &self,
        journey: &str,
        request: &str,
        now: &str,
    ) -> Result<String, String> {
        let request: SaveAsRouteRequest = read("save-as-route request", request)?;
        Ok(json(&self.save_as_route(
            &journey_id(journey)?,
            &request,
            now,
        )?))
    }

    /// B9: proposes re-linking `journey`: `request` is the JSON of a [`RelinkRequest`].
    ///
    /// # Errors
    ///
    /// The JSON of a [`HostError`].
    #[wasm_bindgen(js_name = proposeRelink)]
    pub fn relink_json(&self, journey: &str, request: &str, now: &str) -> Result<String, String> {
        let request: RelinkRequest = read("relink request", request)?;
        Ok(json(&self.relink(&journey_id(journey)?, &request, now)?))
    }
}
