#!/usr/bin/env bash
# Generates briefs/proof/2.5/README.md: the fixtures walked through derive's passes 6 and 7 by
# `cargo run -p cairn-engine --example rank_walkthrough -- fixtures` (the vendor evaluation's
# ranked frontier after it is created, after its up-front decisions, and after kickoff, checked
# against the table fixtures/README.md states, with each node's rank terms and top
# contributions; the product launch ranked globally and for two viewers; effort-adjusted
# ordering), the passes' cost at the limits, the brief's test suites, and the planted bug
# (gravity summed along every path, so a diamond's bottom counts twice, caught by the
# count-once scenario, then passing again once restored). Exits non-zero if any outcome
# differs from the one expected.
#
# usage: briefs/proof/2.5/prove.sh WORK_DIR
#
# WORK_DIR holds a copy of the tree for the planted bug; the repository itself is never
# modified, apart from the README this writes.
# shellcheck disable=SC2016 # backticks in single quotes are Markdown code spans
set -euo pipefail
repo=$(cd "$(dirname "$0")/../../.." && pwd)
work=${1:?usage: prove.sh WORK_DIR}
mkdir -p "$work"
work=$(cd "$work" && pwd)
readme=$repo/briefs/proof/2.5/README.md
export CARGO_TERM_COLOR=never MISE_TRUSTED_CONFIG_PATHS=$work/tree
mismatches=0
out=$readme.tmp
miss() {
  mismatches=$((mismatches + 1))
  echo "prove.sh: $1" >&2
}

cd "$repo"
cat >"$out" <<'EOF'
# Proof for brief 2.5: gravity, leverage, and rank

Generated by `briefs/proof/2.5/prove.sh WORK_DIR`; do not edit by hand. The script fails if
any outcome below differs from the one expected.

What this shows: a journey's frontier is now ranked, and every rank explains itself. `derive`
gives each node its gravity (its own weight and that of everything downstream of it, each node
once, undecided nodes at half, terminal nodes traversed but not counted, not-relevant branches
pruned) with the nodes that make it up; for every node in the normalization set, what
completing it would unblock (through derived group completion and kept work) and its leverage,
with the split by owner; and a rank blending urgency, lateness, and normalized gravity and
leverage, with its terms. The frontiers come in rank order with the PRD's tie order; a viewer
can re-rank for themselves without changing the shared rank; and the frontier can be ordered
by gravity per estimated day. The engine's `Derived` now projects onto the schema's, which
carries all of it to the API. Every derive below is at 2026-10-06, the scenario matrix's clock,
under the default rank constants. The sections are printed by
`cargo run -p cairn-engine --example rank_walkthrough -- fixtures`.

EOF

status=0
walkthrough=$(mise exec -- cargo run --quiet --locked -p cairn-engine --all-features --example rank_walkthrough -- fixtures 2>&1 | grep -v '^mbx') || status=$?
[ "$status" -eq 0 ] || miss "the walkthrough failed: $walkthrough"
printf '%s\n' "$walkthrough" >>"$out"

# The ranked frontier table is what fixtures/README.md states, row for row.
stated=0
while IFS= read -r line; do
  grep -qxF -- "$line" fixtures/README.md || miss "fixtures/README.md does not state: $line"
  stated=$((stated + 1))
done < <(awk '/^## The vendor evaluation.s ranked frontier/ { p = 1 } /^Why each ranks/ { p = 0 } p && /^\| [0-9]/' <<<"$walkthrough")
[ "$stated" -eq 12 ] || miss "expected 12 ranked rows, printed $stated"
grep -qF 'For `e_writer`: `n_kickoff`, `n_beta_start`, `n_launch`' <<<"$walkthrough" || miss "the writer's ranking does not put the beta start before the launch"
grep -qF 'Global order: `n_kickoff`, `n_launch`, `n_beta_start`' <<<"$walkthrough" || miss "the global ranking does not put the launch before the beta start"
grep -qF 'unchanged: true' <<<"$walkthrough" || miss "a per-viewer ranking changed the shared one"
printf '\nThe %s rows of the ranked frontier table above are the ones `fixtures/README.md` states for the vendor evaluation; the J3 matrix entries "vendor evaluation: the ranked frontier ..." and "prioritize for me re-ranks for a viewer ..." check the same values.\n' "$stated" >>"$out"

printf '\n## Cost at the limits\n\n' >>"$out"
status=0
cost=$(mise exec -- cargo test --quiet --locked -p cairn-engine --all-features --test cost_priority -- --nocapture 2>&1) || status=$?
[ "$status" -eq 0 ] || miss "the cost test failed"
{
  printf 'On `generated::date_limits` (2,000 nodes at the depth limit, every weight at `weight_max`): as stored, with every node in its initial state, and that again read on 2026-12-01, when its gated `auto_reach` milestones are due. The budget is one operation per word of a row for each pruned gate edge (the count-once union) and each instant, pruned edge, and kept-work entry once (every leverage simulation together), once more for each overdue, gated `auto_reach` milestone:\n\n```\n'
  grep -E '^(priority|projected) at the limits' <<<"$cost"
  printf '```\n'
} >>"$out"

printf '\n## The suites\n\n' >>"$out"
status=0
suites=$(mise exec -- cargo test --quiet --locked -p cairn-engine --all-features \
  --test priority --test rank --test matrix --test property_priority --test cost_priority 2>&1) || status=$?
[ "$status" -eq 0 ] || miss "the suites failed"
{
  printf 'Passes 6 and 7 by example, the J3 matrix with this brief'"'"'s entries, the property tests (gravity against a plain count-once walk, leverage against derive after completing the node), and the cost test. In cargo'"'"'s order: `cost_priority.rs`, `matrix.rs`, `priority.rs`, `property_priority.rs`, `rank.rs`:\n\n```\n'
  grep -E '^test result' <<<"$suites" | sed -E 's/; finished in .*//'
  printf '```\n'
} >>"$out"

printf '\n## Planted bug: a diamond'"'"'s bottom counted twice\n\n' >>"$out"
tree=$work/tree
rsync -a --delete --exclude target --exclude node_modules --exclude .jj --exclude .git "$repo/" "$tree/"
priority=$tree/crates/engine/src/derive/priority.rs
# Gravity as a sum along every path: each instant adds its dependents' sums and the weight of
# each node whose own work it reaches, so a node reached two ways counts twice.
perl -0pi -e '
  s/(        let mut operations = 0_u64;\n)/$1        let mut sums = vec![0_u64; dependencies.node_count() * Point::ALL.len()];\n/;
  s/(                reach\.union\(instant\.slot\(\), edge\.dependent\.slot\(\)\);\n)/$1                let work = edge.source == super::dependencies::EdgeSource::Work;\n                let own = if work { self.counted_at(edge.dependent.node.get()) } else { 0 };\n                let below = sums.get(edge.dependent.slot()).copied().unwrap_or(0);\n                if let Some(sum) = sums.get_mut(instant.slot()) {\n                    *sum += own + below;\n                }\n/;
  s/(            \.collect\(\);\n)(        self\.operations \+= operations;)/$1        self.path_sums = (0..dependencies.node_count())\n            .map(|at| sums.get(Instant::new(NodeIndex::from_position(at), Point::Finish).slot()).copied().unwrap_or(0))\n            .collect();\n$2/;
  s/let rest: u64 = self\s*\.downstream_of\(at\)\s*\.map\(\|other\| self\.counted_at\(other\)\)\s*\.sum\(\);/let rest: u64 = self.path_sums.get(at).copied().unwrap_or(0);/;
  s/(    gravity: Vec<Score>,\n)/$1    path_sums: Vec<u64>,\n/;
  s/(            gravity: Vec::new\(\),\n)/$1            path_sums: Vec::new(),\n/;
' "$priority"
[ "$(grep -c 'path_sums' "$priority")" -eq 4 ] || miss "the planted bug did not apply"
status=0
planted_output=$(cd "$tree" && mise exec -- cargo test --quiet --all-features -p cairn-engine --test priority 2>&1) || status=$?
[ "$status" -ne 0 ] || miss "the planted bug went unnoticed"
grep -q "a_diamond_counts_its_bottom_once" <<<"$planted_output" || miss "the count-once scenario did not fail"
# cp, not rsync -a: a fresh mtime makes cargo rebuild the restored file.
cp "$repo/crates/engine/src/derive/priority.rs" "$priority"
status_after=0
after_output=$(cd "$tree" && mise exec -- cargo test --quiet --all-features -p cairn-engine --test priority 2>&1) || status_after=$?
[ "$status_after" -eq 0 ] || miss "the restored pass fails"
{
  printf 'In `crates/engine/src/derive/priority.rs` gravity is summed along every path from a node instead of over its count-once downstream set. `cargo test -p cairn-engine --test priority` exit status %s:\n\n```\n' "$status"
  grep -E "^thread '|^  left|^ right|^test result" <<<"$planted_output" | sed -E "s/ \\([0-9]+\\)//; s/; finished in .*//" | head -6
  printf '```\n\nRestored, exit status %s:\n\n```\n' "$status_after"
  grep -E '^test result' <<<"$after_output" | sed -E 's/; finished in .*//'
  printf '```\n'
} >>"$out"

mv "$out" "$readme"
if [ "$mismatches" -gt 0 ]; then
  echo "prove.sh: $mismatches outcome(s) differed from the expected" >&2
  exit 1
fi
echo "prove.sh: every outcome was the expected one; wrote $readme"
