#!/usr/bin/env bash
# Generates briefs/proof/4.7/README.md: the binary as a deployment runs it. A fresh
# directory with a config file and a database seeded with the fixtures; `cairn version` and
# `cairn config check`; startup refused for a missing time zone and public URL and for
# invalid rank constants, each named; `cairn serve` answering the UI and the API on one
# port (capabilities, a fixture journey's document and snapshot, the page and its wasm
# module), refusing a foreign Host before auth, its JSON logs and metrics; a clean stop on
# SIGTERM; and the socket-level SSE write stall, timed by its acceptance test. Exits
# non-zero if any outcome differs from the one expected.
#
# usage: briefs/proof/4.7/prove.sh WORK_DIR
#
# WORK_DIR holds the deployment's files; the repository is never modified apart from the
# README this writes and the build outputs (the web build, the binary). Needs `npm ci`.
# shellcheck disable=SC2016 # backticks in single quotes are Markdown code spans
set -euo pipefail
repo=$(cd "$(dirname "$0")/../../.." && pwd)
work=${1:?usage: prove.sh WORK_DIR}
mkdir -p "$work"
work=$(cd "$work" && pwd)
readme=$repo/briefs/proof/4.7/README.md
out=$readme.tmp
export CARGO_TERM_COLOR=never
# Only the files below configure the binary: none of the caller's CAIRN_ variables
# (overrides or secrets) reaches it or anything else this runs.
while IFS= read -r variable; do
  unset "$variable"
done < <(compgen -e | grep '^CAIRN_' || true)
mismatches=0
miss() {
  mismatches=$((mismatches + 1))
  echo "prove.sh: $1" >&2
}

cd "$repo"
mise run build:web >"$work/build-web.log" 2>&1 || { cat "$work/build-web.log" >&2; exit 1; }
mise exec -- cargo build --quiet --locked -p cairn --bin cairn --example seed_fixtures
target_dir=$(mise exec -- cargo metadata --no-deps --format-version 1 --locked | node -e '
  let text = "";
  process.stdin.on("data", (chunk) => (text += chunk)).on("end", () => console.log(JSON.parse(text).target_directory));')
cairn=$target_dir/debug/cairn
seed=$target_dir/debug/examples/seed_fixtures

deployment=$work/deployment
rm -rf "$deployment"
mkdir -p "$deployment"
port=$(node -e 'const s = require("net").createServer(); s.listen(0, "127.0.0.1", () => { console.log(s.address().port); s.close(); });')
cat >"$deployment/cairn.toml" <<EOF
database = "cairn.db"
listen = "127.0.0.1:$port"
public_url = "http://127.0.0.1:$port/"
timezone = "UTC"

[[auth]]
kind = "dev"
name = "dev"
user = "Dev"
EOF

# Runs a command in the deployment directory, recording its output and exit status.
run() {
  local status=0
  (cd "$deployment" && "$@") >"$work/run.out" 2>&1 || status=$?
  echo "$status" >"$work/run.status"
}
block() {
  printf '\n```console\n$ %s\n' "$1"
  cat "$work/run.out"
  printf '[exit status %s]\n```\n' "$(cat "$work/run.status")"
}

cat >"$out" <<'EOF'
# Proof for brief 4.7: the binary

Generated by `briefs/proof/4.7/prove.sh WORK_DIR`; do not edit by hand. The script fails if
any outcome below differs from the one expected.

What this shows: Cairn now runs as one binary. A directory holding a config file and a
database file is a deployment: `cairn serve` answers the UI, the HTTP API, MCP, and the
revision stream on one port; startup refuses a configuration missing what a deployment must
choose, naming it; requests naming another host are refused before auth; logs are JSON and
metrics are Prometheus text; SIGTERM stops it cleanly. The database here was seeded with
every fixture through the service (`crates/cairn/examples/seed_fixtures.rs`), as the browser
tests that run against the binary seed theirs.
EOF

run "$cairn" version
grep -q "^cairn .* (engine .*)$" "$work/run.out" || miss "version"
{
  printf '\n## Version and configuration\n'
  block "cairn version"
} >>"$out"
run "$cairn" config check --config cairn.toml
[ "$(cat "$work/run.status")" = 0 ] || miss "config check of a valid file"
{
  printf '\nThe deployment'"'"'s file, checked without opening the database or listening:\n\n```toml\n%s\n```\n' "$(sed "s/$port/PORT/g" "$deployment/cairn.toml")"
  block "cairn config check --config cairn.toml"
} >>"$out"
sed -i "s/$port/PORT/g" "$out"

grep -v -e '^timezone' -e '^public_url' "$deployment/cairn.toml" >"$deployment/incomplete.toml"
run "$cairn" serve --config incomplete.toml
grep -q "timezone:" "$work/run.out" && grep -q "public_url:" "$work/run.out" \
  && [ "$(cat "$work/run.status")" != 0 ] || miss "a missing time zone and public URL"
[ ! -e "$deployment/incomplete.db" ] || miss "a database opened"
{
  printf '\n## Startup refuses what a deployment must choose, naming it\n\nThe same file without `timezone` and `public_url`:\n'
  block "cairn serve --config incomplete.toml"
} >>"$out"
{ cat "$deployment/cairn.toml"; printf '\n[rank]\nurgency = 0.5\nundecided_discount = 1.5\nhorizon_days = 0\n'; } >"$deployment/rank.toml"
run "$cairn" serve --config rank.toml
[ "$(grep -c '^  rank' "$work/run.out")" = 3 ] && [ "$(cat "$work/run.status")" != 0 ] || miss "rank constants"
{
  printf '\nRank constants are checked at startup: the blend weights must sum to one, the undecided discount lie within 0 to 1, the horizon be at least a day:\n'
  block "cairn serve --config rank.toml"
} >>"$out"

"$seed" "$deployment/cairn.db"
(cd "$deployment" && exec "$cairn" serve --config cairn.toml 2>"$work/serve.log") &
server=$!
for _ in $(seq 1 100); do
  grep -q '"listening"' "$work/serve.log" 2>/dev/null && break
  sleep 0.1
done
grep -q '"listening"' "$work/serve.log" || { cat "$work/serve.log" >&2; kill "$server"; exit 1; }
base=http://127.0.0.1:$port

# The arguments as a shell would take them: single-quoted where they hold anything but
# plain URL and option characters (none holds a single quote).
quoted() {
  local argument words=()
  for argument in "$@"; do
    if [[ $argument =~ ^[A-Za-z0-9_:/.=-]+$ ]]; then words+=("$argument"); else words+=("'$argument'"); fi
  done
  echo "${words[*]}"
}

# Sends one request with curl, records the status line, headers worth showing, and the body
# cut to `limit` characters.
request() {
  local title=$1 expected=$2 limit=$3
  shift 3
  local status
  status=$(curl -s -o "$work/body" -D "$work/head" -w '%{http_code}' "$@")
  [ "$status" = "$expected" ] || miss "$title: $status, expected $expected"
  {
    printf '\n### %s\n\n```console\n$ curl %s\n' "$title" "$(quoted "$@" | sed "s/$port/PORT/g")"
    head -1 "$work/head" | tr -d '\r'
    grep -i -e '^content-type' -e '^cache-control' "$work/head" | tr -d '\r'
    if [ "$limit" -gt 0 ]; then
      echo
      head -c "$limit" "$work/body" | sed "s/$port/PORT/g"
      [ "$(wc -c <"$work/body")" -le "$limit" ] || printf '... (%s bytes in all)' "$(wc -c <"$work/body")"
      echo
    fi
    printf '```\n'
  } >>"$out"
}

printf '\n## One port: the UI and the API\n\n`cairn serve --config cairn.toml`, then:\n' >>"$out"
request "Capabilities: no assistant configured, so none offered" 200 400 "$base/capabilities"
grep -q '"assistant":false' "$work/body" || miss "assistant offered"
request "A fixture journey's domain document" 200 400 "$base/journeys/j_hiring/document"
request "Its agent snapshot (I3)" 200 600 "$base/journeys/j_hiring/snapshot"
request "The UI's page, from the embedded web build" 200 300 "$base/"
wasm=$(grep -o 'assets/[^"]*\.js' "$work/body" | head -1)
[ -n "$wasm" ] || miss "the page names no bundle"
module=$(cd "$repo/web/app/dist/build" && ls assets/*.wasm | head -1)
request "The browser host's wasm module, cached for good" 200 0 -I "$base/$module"

printf '\n## A foreign Host is refused before auth\n\nA page rebound by DNS to this address names its own host; it is refused on every surface (DECISIONS.md, 4.3 review round 1, 4.7):\n' >>"$out"
request "The API, from another host" 421 200 -H "Host: attacker.example:$port" "$base/capabilities"
request "MCP, from another host" 421 200 -X POST -H "Host: attacker.example" "$base/mcp"
request "The UI, from another host" 421 200 -H "Host: attacker.example" "$base/"
request "A loopback name is served on this loopback listener" 200 200 -H "Host: localhost:$port" "$base/capabilities"

printf '\n## A write, through the API\n' >>"$out"
request "A patch renaming the journey, committed to the database file" 200 300 \
  -H 'content-type: application/json' \
  --data '{"patch":{"id":"p_proof_rename","target":{"journey":"j_hiring"},"base_revision":6,"mutations":[{"op":"edit_journey","name":"Hire a platform engineer, renamed"}]}}' \
  "$base/journeys/j_hiring/patches"

printf '\n## Metrics and logs\n' >>"$out"
request "Prometheus metrics behind the auth layer (the dev provider signs this request in)" 200 0 "$base/metrics"
{
  printf '\nThe series it holds now:\n\n```text\n'
  grep -o '^cairn_[a-z_]*' "$work/body" | sort -u
  printf '```\n'
} >>"$out"
for name in cairn_api_requests_total cairn_api_patches_total cairn_derive_duration_seconds cairn_store_commit_duration_seconds; do
  grep -q "^$name" "$work/body" || miss "metric $name"
done

kill -TERM "$server"
status=0
wait "$server" || status=$?
[ "$status" = 0 ] || miss "the server's exit status on SIGTERM: $status"
{
  printf '\nThe server'"'"'s log (standard error), JSON lines; the last after SIGTERM, which it exited on with status %s:\n\n```json\n' "$status"
  grep -e '"listening"' -e '/journeys/{id}/document' -e 'does not serve' -e 'stopping' "$work/serve.log" | head -6 | sed "s/$port/PORT/g"
  printf '```\n'
} >>"$out"

printf '\n## A subscriber that stops reading loses its slot at the write stall\n\n' >>"$out"
status=0
mise exec -- cargo test --quiet --locked -p cairn --test server -- --exact \
  in_process::a_subscriber_that_stops_reading_loses_its_slot_at_the_write_stall --nocapture \
  >"$work/stall.log" 2>&1 || status=$?
[ "$status" = 0 ] || miss "the write stall test"
{
  printf 'The acceptance test (`crates/cairn/tests/server.rs`) opens the revision stream with the smallest receive buffer the kernel allows, stops reading while the stream keeps ticking, and times the slot from the moment its receive window closed. `TCP_USER_TIMEOUT` at the 15 s stall closes the connection in the kernel, long before the server'"'"'s send buffer could fill (DECISIONS.md, 4.2, 4.7). Its measurement, exit status %s:\n\n```text\n' "$status"
  grep '^freed' "$work/stall.log"
  printf '```\n'
} >>"$out"

mv "$out" "$readme"
if [ "$mismatches" -gt 0 ]; then
  echo "prove.sh: $mismatches outcome(s) differed" >&2
  exit 1
fi
echo "wrote $readme"
