#!/usr/bin/env bash
# Generates briefs/proof/1.2/README.md: the fixtures round-tripping byte for byte, documents
# the schema rejects with the path to what is wrong, limits at and past their values, a key
# where an id belongs, the generated JSON Schema rejecting what the parser rejects, and the
# planted bug (one limit check removed, its test failing, then passing again). Exits non-zero
# if any outcome differs from the one expected.
#
# usage: briefs/proof/1.2/prove.sh WORK_DIR
#
# WORK_DIR holds the planted documents and a copy of the tree for the planted bug; the
# repository itself is never modified, apart from the README this writes.
# shellcheck disable=SC2016 # backticks in single quotes are Markdown code spans
set -euo pipefail
repo=$(cd "$(dirname "$0")/../../.." && pwd)
work=${1:?usage: prove.sh WORK_DIR}
mkdir -p "$work"
work=$(cd "$work" && pwd)
readme=$repo/briefs/proof/1.2/README.md
export CARGO_TERM_COLOR=never MISE_TRUSTED_CONFIG_PATHS=$work/tree
mismatches=0
out=$readme.tmp

cd "$repo"
mise exec -- cargo build --quiet --locked -p cairn-schema --bin cairn-document
document() {
  local binary
  binary=$(mise exec -- cargo metadata --format-version 1 --no-deps --locked \
    | node -e 'let t="";process.stdin.on("data",c=>t+=c).on("end",()=>console.log(JSON.parse(t).target_directory))')/debug/cairn-document
  "$binary" "$@"
}

# expect TITLE EXPECTED(0|1) TYPE FILE: runs cairn-document and records the outcome.
expect() {
  local title=$1 expected=$2 kind=$3 file=$4 output status=0
  output=$(document "$kind" "$file" 2>&1) || status=$?
  if [ "$status" -ne "$expected" ]; then
    mismatches=$((mismatches + 1))
    echo "prove.sh: MISMATCH in '$title': expected exit $expected, got $status" >&2
  fi
  # A document that parses is summarized; one that does not shows its error.
  if [ "$status" -eq 0 ]; then
    output="parsed; canonical form is $(wc -l <<<"$output" | tr -d ' ') lines"
  fi
  printf '\n### %s\n\n`cairn-document %s %s` exit status: %s (expected %s).\n\n```\n%s\n```\n' \
    "$title" "$kind" "${file#"$work"/}" "$status" "$expected" "$output" >>"$out"
}

cat >"$out" <<'EOF'
# Proof for brief 1.2: schema and fixtures

Generated by `briefs/proof/1.2/prove.sh WORK_DIR`; do not edit by hand. The script fails if
any outcome below differs from the one expected.

What this shows: the shared types parse and write the PRD's documents deterministically.
Every fixture is in canonical form (parsing and writing it gives the same bytes); a document
that breaks a kind restriction, a limit, or the key/id distinction fails to parse with the
path to the failing value; the generated JSON Schema rejects what the parser rejects; and a
limit check, removed, is caught by its test. `cairn-document` (crates/schema) parses a
document of a given type and prints its canonical YAML, or the error.

## Fixtures round-trip byte for byte
EOF

{
  printf '\n| File | Bytes | Canonical output |\n|---|---|---|\n'
  for file in fixtures/*/route.yaml fixtures/*/journey.yaml; do
    kind=scenario
    [ "${file##*/}" = route.yaml ] && kind=route-file
    if document "$kind" "$file" | cmp -s - "$file"; then verdict="identical"; else verdict="DIFFERS"; mismatches=$((mismatches + 1)); fi
    printf '| `%s` | %s | %s |\n' "$file" "$(wc -c <"$file" | tr -d ' ')" "$verdict"
  done
} >>"$out"

printf '\n## Rejected with a path\n' >>"$out"
planted=$work/planted
mkdir -p "$planted"

# A1a: an estimate on a milestone.
sed '/^  title: Decision meeting$/a\  estimate: 2' fixtures/vendor-evaluation/route.yaml >"$planted/estimate-on-milestone.yaml"
expect "A1a: an estimate on a milestone (the decision meeting)" 1 route-file "$planted/estimate-on-milestone.yaml"

# A1a: fills_role on a date decision.
sed '/^  feeds_milestone: decision-meeting$/a\  fills_role: eval_owner' fixtures/vendor-evaluation/route.yaml >"$planted/fills-role-on-date.yaml"
expect "A1a: fills_role on a date decision" 1 route-file "$planted/fills-role-on-date.yaml"

# A key where a path belongs is fine in a file only when it is a valid path; in the graph
# form, a path where a key belongs is not a key.
cat >"$planted/path-for-key.json" <<'EOF'
{"nodes":[{"key":"n_plan","id":"plan","kind":"action","title":"Plan","requires":["setup/access"]}]}
EOF
expect "A path where the graph form needs a key" 1 graph "$planted/path-for-key.json"
cat >"$planted/role-key-for-node-key.json" <<'EOF'
{"nodes":[{"key":"r_plan","id":"plan","kind":"action","title":"Plan"}]}
EOF
expect "A role key where a node key belongs" 1 graph "$planted/role-key-for-node-key.json"

printf '\n## Limits at and past their values\n' >>"$out"
nodes() {
  printf 'format: 1\nroute: big\nname: Big\nnodes:\n'
  for index in $(seq 1 "$1"); do printf -- '- id: n%s\n  kind: action\n  title: Step\n' "$index"; done
}
nodes 2000 >"$planted/nodes-2000.yaml"
nodes 2001 >"$planted/nodes-2001.yaml"
expect "node_count_max (2,000): 2,000 nodes parse" 0 route-file "$planted/nodes-2000.yaml"
expect "node_count_max (2,000): 2,001 nodes do not" 1 route-file "$planted/nodes-2001.yaml"

choices() {
  printf 'format: 1\nroute: wide\nname: Wide\nnodes:\n- id: pick\n  kind: decision\n  title: Pick\n  prompt: Which?\n  answer_type: single_choice\n  choices:\n'
  for index in $(seq 1 "$1"); do printf -- '  - c%s\n' "$index"; done
}
choices 32 >"$planted/choices-32.yaml"
choices 33 >"$planted/choices-33.yaml"
expect "choice_count_per_decision_max (32): 32 choices parse" 0 route-file "$planted/choices-32.yaml"
expect "choice_count_per_decision_max (32): 33 do not" 1 route-file "$planted/choices-33.yaml"

sed 's/^  estimate: 2$/  estimate: 365/' fixtures/vendor-evaluation/route.yaml >"$planted/estimate-365.yaml"
sed 's/^  estimate: 2$/  estimate: 366/' fixtures/vendor-evaluation/route.yaml >"$planted/estimate-366.yaml"
expect "offset_days_max (365): an estimate of 365 days parses" 0 route-file "$planted/estimate-365.yaml"
expect "offset_days_max (365): 366 does not" 1 route-file "$planted/estimate-366.yaml"

printf '\n## The generated JSON Schema agrees with the parser\n\n' >>"$out"
status=0
schema_output=$(mise exec -- cargo test --quiet --locked -p cairn-schema --test json_schema --test fixtures 2>&1) || status=$?
[ "$status" -eq 0 ] || { mismatches=$((mismatches + 1)); echo "prove.sh: schema tests failed" >&2; }
{
  printf '`schema/route-file.schema.json` is generated from the parser'"'"'s own type. Every fixture route file validates against it, and the documents the parser rejects for a kind restriction or an unknown field fail validation too (`crates/schema/tests/json_schema.rs`, `fixtures.rs`):\n\n```\n'
  grep -E '^test result|^running' <<<"$schema_output"
  printf '```\n'
} >>"$out"

printf '\n## Planted bug: a limit check removed\n\n' >>"$out"
tree=$work/tree
rsync -a --delete --exclude target --exclude node_modules --exclude .jj --exclude .git "$repo/" "$tree/"
target='Limit::ConditionDepth.check(depth).map_err(ConditionError::TooLarge)?;'
condition=$tree/crates/schema/src/condition.rs
perl -0pi -e 's/\n\s*Limit::ConditionDepth\s*\.check\(depth\)\s*\.map_err\(ConditionError::TooLarge\)\?;//' "$condition"
if cmp -s "$condition" "$repo/crates/schema/src/condition.rs"; then
  mismatches=$((mismatches + 1))
  echo "prove.sh: the planted check was not found" >&2
fi
status=0
planted_output=$(cd "$tree" && mise exec -- cargo test --quiet -p cairn-schema --lib condition:: 2>&1) || status=$?
[ "$status" -ne 0 ] || { mismatches=$((mismatches + 1)); echo "prove.sh: the planted bug went unnoticed" >&2; }
# cp, not rsync -a: a fresh mtime makes cargo rebuild the restored file.
cp "$repo/crates/schema/src/condition.rs" "$tree/crates/schema/src/condition.rs"
status_after=0
after_output=$(cd "$tree" && mise exec -- cargo test --quiet -p cairn-schema --lib condition:: 2>&1) || status_after=$?
[ "$status_after" -eq 0 ] || { mismatches=$((mismatches + 1)); echo "prove.sh: the restored check fails" >&2; }
{
  printf 'Removed from `crates/schema/src/condition.rs`: `%s` (the condition depth check). `cargo test -p cairn-schema --lib condition::` exit status %s:\n\n```\n' "$target" "$status"
  grep -E 'panicked|depth_at_and_past|^test result' <<<"$planted_output" | sed -E 's/ \([0-9]+\)//' | head -5
  printf '```\n\nRestored, exit status %s:\n\n```\n' "$status_after"
  grep -E '^test result' <<<"$after_output"
  printf '```\n'
} >>"$out"

mv "$out" "$readme"
if [ "$mismatches" -gt 0 ]; then
  echo "prove.sh: $mismatches outcome(s) differed from the expected" >&2
  exit 1
fi
echo "prove.sh: every outcome was the expected one; wrote $readme"
